### ISSUE TITLE
I scanned qr code successfully but no bot installed on whatsapp

### ISSUE THREAD

**Issue by rajareddy4556** [askrella/whatsapp-chatgpt#102]
I scanned qr code successfully but no bot installed on whatsapp

**Comment by navopw** [comment]
Can you provide more details? Log outputs? Screenshots?

**Comment by rajareddy4556** [comment]
![2023-02-24](https://user-images.githubusercontent.com/68636215/221126945-c60262b9-79a2-4ca6-a238-ccbb77c6c15f.png)
i am done nothing happened to whatsapp

**Comment by connorv001** [comment]
Can you give some more details how did you test the both

**Comment by navopw** [comment]
> ![2023-02-24](https://user-images.githubusercontent.com/68636215/221126945-c60262b9-79a2-4ca6-a238-ccbb77c6c15f.png) i am done nothing happened to whatsapp

This looks good, the bot is up and running.

Try texting yourself on whatsapp `!gpt test``

You can message yourself: https://askrella.github.io/whatsapp-chatgpt/#/pages/send-messages-to-yourself
