### ISSUE TITLE
Pip install torch, could not find a version

### ISSUE THREAD

**Issue by Re1da** [askrella/whatsapp-chatgpt#106]
Yes. Doesn't work.
```

pi@pi:~ $ pip install torch
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

```

I also tried other methods to install PyTorch.

_Originally posted by @byt3magic in https://github.com/askrella/whatsapp-chatgpt/issues/105#issuecomment-1443650619_

**Comment by navopw** [comment]
This issue is not bot related but maybe someone can help here.

I dont have a Raspberry Pi right now on me, might test it later this week.

**Comment by Re1da** [comment]
Reda
