### ISSUE TITLE
In my whatsapp I am connect to a MacOS device although i dont have a mac

### ISSUE THREAD

**Issue by ai22m031** [askrella/whatsapp-chatgpt#107]
Since i used this api, i have an additional device connect to my whatsapp web devices. Somehow its named with macos although i dont have a mac device.

Is this because of the whatsapp-chatgpt bot? Because I like the application, but i dont like that some random persons have access to my convos with other people..

**Comment by navopw** [comment]
Remove this mac device, your QR code might was compromised somehow.

It's not the whatsapp-chatgpt bot if you dont have a Mac.

**Comment by tmankar19** [comment]
i had the same issue. I scanned the QR code and it shows that its linked to a mac
