### ISSUE TITLE
After having installed Whisper by bot is officially a russian speaker. HELPP

### ISSUE THREAD

**Issue by kingofkillers91** [askrella/whatsapp-chatgpt#115]
Hi there, 
my bot is transcribing audio into russian even though i never set that languange. How can i change that?
  [Transcription] Transcribing audio with "local" mode...
/home/alessandro/Myproject1/lib/python3.11/site-packages/whisper/transcribe.py:79: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
◇  [Transcription] Transcription response: Браво, браво, браво, браво... (language: Russian)
◇  [GPT] Received prompt from 393387891753@c.us: Браво, браво, браво, браво...
◇  [GPT] Received prompt from 393387891753@c.us: ciao
◇  [GPT] Answer to 393387891753@c.us: Hi there! How can I help you?  | OpenAI request took 1179ms)
◇  [GPT] Answer to 393387891753@c.us: Спасибо, я делаю свою работу!  | OpenAI request took 2904ms)
◇  [GPT] Received prompt from 393387891753@c.us: hi there
◇  [GPT] Answer to 393387891753@c.us: Привет! Как я могу вам помочь?  | OpenAI request took 2250ms)
Thanks

**Comment by navopw** [comment]
What was your actual prompt you said in the voice message and in which language?

If voice messages are under 30 seconds long, it's sometimes hard for OpenAI whisper to detect the language correctly.

**Comment by kingofkillers91** [comment]
So made a 30 seconds audio in italian first and then english.. It translated only like 2 seconds of the italian audio and then crashed when i sent the 30 seconds english audio.----- > [Transcription] Transcribing audio with "local" mode...
/home/alessandro/Myproject1/lib/python3.11/site-packages/whisper/transcribe.py:79: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
◇  [Transcription] Transcription response: ciao come sta io tutto tutto bene e senti niente ti volevo dire se ti (language: Italian)
◇  [GPT] Received prompt from 393387891753@c.us: ciao come sta io tutto tutto bene e senti niente ti volevo dire se ti
◇  [GPT] Answer to 393387891753@c.us: Ciao! Tutto bene, grazie per avermi chiesto. Che cosa volevi dirmi?  | OpenAI request took 1765ms)
◇  [Transcription] Transcribing audio with "local" mode...
/home/alessandro/Myproject1/lib/python3.11/site-packages/whisper/transcribe.py:79: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
◇  [Transcription] Transcription response: Matt, um, Aki, see yourself and just talk for 30 seconds about what I don't know what to say. (language: English)
◇  [GPT] Received prompt from 393387891753@c.us: Matt, um, Aki, see yourself and just talk for 30 seconds about what I don't know what to say.
/home/alessandro/Desktop/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:36:67)
    at __puppeteer_evaluation_script__:10:45
    at ExecutionContext._evaluateInternal (/home/alessandro/Desktop/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/home/alessandro/Desktop/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.sendMessage (/home/alessandro/Desktop/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/src/Client.js:686:28)
