### ISSUE TITLE
 Chromium revision (982053)

### ISSUE THREAD

**Issue by ysfcn2001** [askrella/whatsapp-chatgpt#116]
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
I run "npm install" but not working
t run "npm i chromium " and "chromium --save" but not working

**Comment by connorv001** [comment]
What platform you rinning this on?

**Comment by ysfcn2001** [comment]
Windows-VScode

**Comment by MikelCalvo** [comment]
Hi @ysfcn2001, this happened to me too. 
I found the following fix:
Open a terminal on the project folder and type the following:
`cd .\node_modules\whatsapp-web.js\node_modules\puppeteer\`
and then `npm install` it will install the correct version (it may take a while to download everything).
then change back into the repository folder and type `npm run start`

Hope that helped!

**Comment by ysfcn2001** [comment]
@MikelCalvo muchas gracias
