### ISSUE TITLE
Error model's maximum context length

### ISSUE THREAD

**Issue by AlessandroAnnini** [askrella/whatsapp-chatgpt#117]
I get this error every time I write something, even with `!gpt hello`

```bash
An error occured Error: This model's maximum context length is 4096 tokens. However, you requested 4250 tokens (154 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.

at ChatGPT.askStream (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:152:11)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at ChatGPT.ask (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:97:10)
at Module.handleMessageGPT (/app/src/handlers/gpt.ts:39:15)
at Module.handleIncomingMessage (/app/src/handlers/message.ts:119:3)
at Client.<anonymous> (/app/src/index.ts:84:3)
```

**Comment by navopw** [comment]
Please increase your MAX_MODEL_TOKENS in the .env.

This will solve your problem since the prompt is also count for token length.

**Comment by AlessandroAnnini** [comment]
I tried already, it won't change even with MAX_MODEL_TOKENS=4096, besides, why should it request 4250 tokens when I write "hello"?

I am using Docker and I set `OPENAI_API_KEY` and `PREFIX_ENABLED` variables in docker-compose file

Can you please reopen this @navopw?

**Comment by AlessandroAnnini** [comment]
I still wasn't able to make it work with docker but starting it with `npm run start`, installing chronium-browser and correctly configuring puppeteer following [this advice](https://github.com/askrella/whatsapp-chatgpt/issues/103#issuecomment-1443447710) in #103 I was finally able to run it ok.

The problem still remains with docker.
