### ISSUE TITLE
Ignoring old message:

### ISSUE THREAD

**Issue by siulynot** [askrella/whatsapp-chatgpt#118]
I just installed the newest version, but i am getting this message on every try i do: 
![image](https://user-images.githubusercontent.com/225342/222528929-f88d42e6-cdf5-449d-bb27-58fddcdabb7f.png)

Any help will be great.

**Comment by navopw** [comment]
This message was sent before you the bot started, is this correct?

**Comment by siulynot** [comment]
No, this message happens when its already authenticated and receiving messages. But every messages comes in the log like this, tagged and non tagged.

**Comment by siulynot** [comment]
![image](https://user-images.githubusercontent.com/225342/222693725-22e706a0-ba7c-4406-bb8b-42ef0abe946b.png)
I start the app, authenticate, and then i keep receiving these messages without response

**Comment by siulynot** [comment]
Update: the app stays in this mode for some time, eventually, when it finally receives a message, it outputs this:

```An error occured, please contact the administrator. (This model's maximum context length is 4096 tokens. However, you requested 4255 tokens (159 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.)```

And then it crashes with this output:

```
◇  [Transcription] Transcribing audio with "local" mode...        /bin/sh: line 1: whisper: command not found
node:internal/errors:867                                            const err = new Error(message);
              ^

Error: Command failed: whisper /tmp/e47e2bde-f83f-4dd0-a0c8-c8cc8f2bc563.wav                                                        /bin/sh: line 1: whisper: command not found
    at checkExecSyncError (node:child_process:885:11)                 at Proxy.execSync (node:child_process:957:15)                     at Module.transcribeAudioLocal (/home/siu/whatsapp-chatgpt/src/providers/whisper-local.ts:14:17)                                    at Module.handleIncomingMessage (/home/siu/whatsapp-chatgpt/src/handlers/message.ts:66:37)                                          at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.<anonymous> (/home/siu/whatsapp-chatgpt/src/index.ts:70:3) {                                                            status: 127,                                                      signal: null,
  output: [ null, '', '/bin/sh: line 1: whisper: command not found\n' ],                                                              pid: 740109,                                                      stdout: '',                                                       stderr: '/bin/sh: line 1: whisper: command not found\n'         }
Node.js v19.6.0
```

**Comment by siulynot** [comment]
Btw, this is the command that executed this output: 
![IMG_20230306_195043.jpg](https://user-images.githubusercontent.com/225342/223282945-ea0e9143-41b8-48ef-b7ef-48ac3044fe4a.jpg)

I noticed the error mentions whisper, but it was a text command.

**Comment by siulynot** [comment]
Any updates on this?

**Comment by navopw** [comment]
whisper: command not found

You have to install the OpenAI Whisper CLI.

Also try to use less MAX_MODEL_TOKENS because the prompt tokens are also counted.

**Comment by siulynot** [comment]
@navopw Hello, i installed Whisper, and reduced MAX_MODEL_TOKENS to what is recommended in the .env-example. But I am still struggling with the "Ignoring old message" issue. 
Every Message is listed like this:
![image](https://user-images.githubusercontent.com/225342/224996154-74d2cc37-e2bf-4957-9e08-6a302da39891.png)

Seems to be more an issue with whatsapp than with openai.

**Comment by siulynot** [comment]
Got it to work finally... it takes like 15min to start accepting prompts.
