### ISSUE TITLE
Error code 401

### ISSUE THREAD

**Issue by ysfcn2001** [askrella/whatsapp-chatgpt#124]
An error occured, please contact the administrator. (Request failed with status code 401)

**Comment by ysfcn2001** [comment]
How can i fix it?

**Comment by ysfcn2001** [comment]
![Screenshot_20230304_221403_WhatsApp.png](https://user-images.githubusercontent.com/89855552/222924612-8db8007f-3a10-4c5f-a95e-6fbc24d7d169.png)

**Comment by navopw** [comment]
Error 401 means your token is invalid.

Make sure you have not whitespaces before or after the token in the .env file.

Also try to revoke it on the OpenAI website and get a new one.

**Comment by hellloooooooooooooo** [comment]
nope. still not working

**Comment by hellloooooooooooooo** [comment]
![Screenshot (260)](https://user-images.githubusercontent.com/125910474/222934938-677de8b7-782a-45ef-9d5a-d7aef5f6c7aa.png)

**Comment by iqbaldal** [comment]
same with me. i also got that error

**Comment by ysfcn2001** [comment]
> Error 401 means your token is invalid.
> 
> Make sure you have not whitespaces before or after the token in the .env file.
> 
> Also try to revoke it on the OpenAI website and get a new one.

It's working thanks

**Comment by mycarlos26** [comment]
![image](https://user-images.githubusercontent.com/11149480/222992771-15245801-453f-47de-b2bd-3a1ac260a12a.png)
same error and the api key is well placed and has no space and is newly created.

**Comment by GreenerX** [comment]
Same thing happens to me.. Is there any fix? I revoked and entered a new API key, still getting the errors

**Comment by navopw** [comment]
@mycarlos26 Revoke your key please, because you showed it here on GIthub.

Guys, I will check this out.

**Comment by cristigoia** [comment]
Same thing happened to me and I made my OpenAI account a Paid Account by adding my credit card [in here](https://platform.openai.com/account/billing/overview) & then it worked.
