### ISSUE TITLE
This model's maximum context length is 4096 tokens

### ISSUE THREAD

**Issue by thenetguy** [askrella/whatsapp-chatgpt#125]
not sure what im doing wrong but I keep getting the below error when trying to use !gpt  , even tho I set the env MAX_MODEL_TOKENS: "4096"
`An error occured, please contact the administrator. (This model's maximum context length is 4096 tokens. However, you requested 4250 tokens (154 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.)`
any suggestions will be greatly appreciated

**Comment by Re1da** [comment]
Duplicate of #

**Comment by thenetguy** [comment]
I'm sorry I don't know what you mean, can you please elaborate?

**Comment by navopw** [comment]
The prompt you are putting in also costs tokens and reduces the limit.

Try a different value, for example:

```
MAX_MODEL_TOKENS=3000
```

**Comment by thenetguy** [comment]
this worked . thank you sir

**Comment by bogdanr** [comment]
It looks like sometimes the message gets overflow with other things than the current message:
```
whatsapp-chatgpt-whatsapp-chatgpt-1  | ◇  [GPT] Received prompt from 40723372866@c.us: hello
whatsapp-chatgpt-whatsapp-chatgpt-1  | An error occured Error: This model's maximum context length is 4096 tokens. However, you requested 4231 tokens (1231 in the messages, 3000 in the completion). Please reduce the length of the messages or completion.
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ChatGPT.askStream (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:152:11)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ChatGPT.ask (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:97:10)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at Module.handleMessageGPT (/app/src/handlers/gpt.ts:27:15)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at Module.handleIncomingMessage (/app/src/handlers/message.ts:119:3)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at Client.<anonymous> (/app/src/index.ts:84:3)

```
Here the message is just hello

**Comment by rivanbello** [comment]
Same problem here.

**Comment by navopw** [comment]
Thats really strange. haven't encountered this before. Can you give me the prompt so I can reproduce this error?

**Comment by kingofkillers91** [comment]
Same error:  [GPT] Received prompt from 17869360334@c.us: hey
whatsapp-chatgpt_1  | ◇  [GPT] New conversation for 17869360334@c.us (ID: 55d53b60-2b31-4613-b593-890a1dcfcf55)
whatsapp-chatgpt_1  | An error occured Error: This model's maximum context length is 4097 tokens. However, you requested 4250 tokens (154 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
whatsapp-chatgpt_1  |     at ChatGPT.askStream (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:152:11)
whatsapp-chatgpt_1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
whatsapp-chatgpt_1  |     at ChatGPT.ask (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:97:10)
whatsapp-chatgpt_1  |     at Module.handleMessageGPT (/app/src/handlers/gpt.ts:63:15)
whatsapp-chatgpt_1  |     at Module.handleIncomingMessage (/app/src/handlers/message.ts:143:3)
whatsapp-chatgpt_1  |     at Client.<anonymous> (/app/src/index.ts:84:3)
I'm running the bot on docker. and i have no idea where i should edit set the max tokens cause there isn't any variable to set that in the docker-compose.yml
