### ISSUE TITLE
[Request] Adding feature usage limits.

### ISSUE THREAD

**Issue by kingofkillers91** [askrella/whatsapp-chatgpt#127]
can you add the feature where the bot randomly remindes you of the  usage limits?
like every 10 cent spent for example (you decide how much) , an alert is sent from the bot. Can you do that?
You are the best!
Thanks

**Comment by manishaarya9899359346** [comment]
Apne vand me bh8 mrwalo don9 mjhse bkl

**Comment by kingofkillers91** [comment]
What?

**Comment by manishaarya9899359346** [comment]
Why yhe fuck uh entered my acciunt uh son of a bitch and that vitch is
gonna die by my hand whom ur helping asshole

**Comment by kingofkillers91** [comment]
U drunk or what?

**Comment by Bilalshaikh15** [comment]
can you assign me?
