### ISSUE TITLE
Error Code 401

### ISSUE THREAD

**Issue by GreenerX** [askrella/whatsapp-chatgpt#129]
Request Failed with Status Code 401
<img width="707" alt="SCR-20230306-kpyj" src="https://user-images.githubusercontent.com/127094608/223075040-0eb79cac-2394-43e9-a36e-1836e6816370.png">
<img width="541" alt="SCR-20230306-kqpj" src="https://user-images.githubusercontent.com/127094608/223075046-87e7b3d7-f8aa-481c-9c61-1498f508b09e.png">
<img width="1195" alt="SCR-20230306-kqys" src="https://user-images.githubusercontent.com/127094608/223075051-407a8651-9d88-427c-be2a-0aa65460edb0.png">
![Screenshot 2023-03-06 at 11 46 26](https://user-images.githubusercontent.com/127094608/223075097-ee20669b-dba9-481f-85b9-97e08dc57283.png)

**Comment by navopw** [comment]
Rename your file to `.env` and try again

**Comment by rivanbello** [comment]
Same problem, but i created .env

**Comment by chrisrusso** [comment]
does this work in Windows?

**Comment by kingofkillers91** [comment]
Same issue.

**Comment by chrisrusso** [comment]
It's the API key... I created a new account and it worked.

**Comment by kingofkillers91** [comment]
Nope, same error. I tried the key from another account

**Comment by krunchosg** [comment]
I'm facing the same 401 error. Tried multiple different accounts and api keys.. all stuck with same error 401. Any idea why? 

is it due to the ChatGPT server busy and refusing to the API calls even when the key is correct?

**Comment by krunchosg** [comment]
An error occured Error: Request failed with status code 401
    at ChatGPT.askStream (file:///C:/Users/kaun.chee.toh/whatsapp-gpt-main/node_modules/chatgpt-official/src/classes/chatgpt.ts:154:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChatGPT.ask (file:///C:/Users/kaun.chee.toh/whatsapp-gpt-main/node_modules/chatgpt-official/src/classes/chatgpt.ts:97:10)
    at Module.handleMessageGPT (C:\Users\kaun.chee.toh\whatsapp-gpt-main\src\handlers\gpt.ts:41:18)
    at Module.handleIncomingMessage (C:\Users\kaun.chee.toh\whatsapp-gpt-main\src\handlers\message.ts:103:5)
    at Client.<anonymous> (C:\Users\kaun.chee.toh\whatsapp-gpt-main\src\index.ts:57:5)

**Comment by krunchosg** [comment]
just for more context. below error msgs. 

An error occured Error: Request failed with status code 401
    at ChatGPT.askStream (file:///C:/Users/k.toh/whatsapp-gpt-main/node_modules/chatgpt-official/src/classes/chatgpt.ts:154:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChatGPT.ask (file:///C:/Users/k.toh/whatsapp-gpt-main/node_modules/chatgpt-official/src/classes/chatgpt.ts:97:10)
    at Module.handleMessageGPT (C:\Users\k.toh\whatsapp-gpt-main\src\handlers\gpt.ts:41:18)
    at Module.handleIncomingMessage (C:\Users\k.toh\whatsapp-gpt-main\src\handlers\message.ts:103:5)
    at Client.<anonymous> (C:\Users\k.toh\whatsapp-gpt-main\src\index.ts:57:5)

**Comment by kingofkillers91** [comment]
for me it's working only if I paste my openai key into the "docker-compose.yml" file and delete or rename the file  .env
With that Configuration I'm not getting any 401 code error and the bot replies to my questions just as usual. but of course I can't add the other variables in that file because when I launch the bot it goes in error again

**Comment by krunchosg** [comment]
> for me it's working only if I paste my openai key into the "docker-compose.yml" file and delete or rename the file .env With that Configuration I'm not getting any 401 code error and the bot replies to my questions just as usual. but of course I can't add the other variables in that file because when I launch the bot it goes in error again

I tried your way but it's still not working. =(

**Comment by krunchosg** [comment]
I'm pretty sure my api key is working as i've tried it on this git >> https://github.com/openai/openai-quickstart-node.git

**Comment by krunchosg** [comment]
i managed to overcome the 401 error by hardcoding my api key in src\config.ts but now there's a new error msg when all i did was prompt "Hello" . how did a Hello end up becoming 4097 tokens?

An error occured Error: This model's maximum context length is 4097 tokens. However, you requested 4251 tokens (155 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.

**Comment by NoobGinger** [comment]
Also getting the error. Bot is working untill you write it on whatsapp :)...

**Comment by basharbachir** [comment]
same here as well

**Comment by fishball82** [comment]
I have experienced this error as well, but it turned out that the OPEN AI API key in the .yml file was wrong. IMO the cause of this error is purely from OpenAI

**Comment by Dagolin** [comment]
For anyone who's struggling for hours (if you read this, ITS YOU) about 401 problem, try

1. close any sessions you have
2. open **db.json** and remove all the incorrect apikeys you can find.
3. **npm run start** again
