### ISSUE TITLE
TTS always generated English voice responses, though the question / transcribedLanguage was German

### ISSUE THREAD

**Issue by jooles** [askrella/whatsapp-chatgpt#132]
Hi there,

this leads to funny behaviour when the TTS Engine reads out German text in English pronunciation ;-)
Is there a possibility to control the language of the generated voice message?

Thanks!

**Comment by navopw** [comment]
Hey @jooles, thats currently not possible.

The generated voice is always english.

Im also German, so I know how funny this is haha 😄

**Comment by MikelCalvo** [comment]
Hi @jooles, with the PR #138 that should be fixed.
AWS Polly contains German voices too.

After downloading the latests commits you can follow the official documentation to get it working: https://askrella.github.io/whatsapp-chatgpt/#/pages/tts?id=aws-polly.
Let me know if you find any issues.

Have a nice day!
