### ISSUE TITLE
Whitelist/blacklist of contacts to work with

### ISSUE THREAD

**Issue by AlessandroAnnini** [askrella/whatsapp-chatgpt#136]
Hi,
It would be nice to have the ability to specify where gpt is active: for example it should work in the chat with myself and with the one with my wife but not on every other chat.

This could be a list of names or, better, telephone numbers.

**Comment by Re1da** [comment]
#134

**Comment by Seitk** [comment]
Actually this https://github.com/askrella/whatsapp-chatgpt/pull/137

**Comment by Seitk** [comment]
https://github.com/askrella/whatsapp-chatgpt/pull/144

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
