### ISSUE TITLE
No prefix for calling gpt?

### ISSUE THREAD

**Issue by zakarque** [askrella/whatsapp-chatgpt#140]
I wonder how can I remove !gpt and let it take any message to go straight to gpt? wanna turn myself to a bot if that make sense 😂

**Comment by steventsao** [comment]
Have you tried removing the `GPT_PREFIX` variable or set it to empty? https://github.com/askrella/whatsapp-chatgpt/blob/master/.env-example#L22 @zakarque

**Comment by zakarque** [comment]
- I tried commenting the prefix line > it uses the default !gpt
- leave blank >> also goes back to default
- * >> uses * instead
