### ISSUE TITLE
Error: Evaluation failed: TypeError: window.Store.DownloadManager.downloadAndDecrypt is not a function

### ISSUE THREAD

**Issue by ImmortalMan01** [askrella/whatsapp-chatgpt#147]
**It crashes when someone sends audio.**

C:\Users\Ogulc\Desktop\Yeni klasör (4)\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: window.Store.DownloadManager.downloadAndDecrypt is not a function
    at __puppeteer_evaluation_script__:20:75
    at ExecutionContext._evaluateInternal (C:\Users\Ogulc\Desktop\Yeni klasör (4)\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (C:\Users\Ogulc\Desktop\Yeni klasör (4)\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at Message.downloadMedia (C:\Users\Ogulc\Desktop\Yeni klasör (4)\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\src\structures\Message.js:387:24)
    at Module.handleIncomingMessage (C:\Users\Ogulc\Desktop\Yeni klasör (4)\whatsapp-chatgpt-master\src\handlers\message.ts:39:19)
    at Client.<anonymous> (C:\Users\Ogulc\Desktop\Yeni klasör (4)\whatsapp-chatgpt-master\src\index.ts:57:5)

Node.js v18.13.0

**Comment by ImmortalMan01** [comment]
I temporarily found the problem myself and came up with a solution. When I delete the "session" folder and open it again, the problem is fixed, but I have to do this every time I open and close the bot or it crashes. **I need a permanent solution can you please help?**

**Comment by doofzoff** [comment]
same, help pls

**Comment by loliuy** [comment]
same when use TRANSCRIPTION_MODE=openai, and when use !dalle ,also shows the error .

**Comment by ImmortalMan01** [comment]
It crashes when they send pictures, not just audio files.

**Comment by doofzoff** [comment]
> It crashes when they send pictures, not just audio files.

yep, or if something send stickers, video, photo, gif and more

**Comment by rikuddo91** [comment]
It also seems to be crashing with !dalle prompt. Only text prompts seems to be working for me.
Deleted the sessions folder and relinked whatsapp, but still same error.

**Comment by renancunhasousa** [comment]
I fix it

declare for window.Store.DownloadManager.downloadAndDecrypt function name change at window.Store.DownloadManager.downloadAndMaybeDecrypt

\node_modules\whatsapp-web.js\src\structures\Message.js line 406

**Comment by renancunhasousa** [comment]
I change also
Injected.js
// window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0];
window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0];
Thank You It's working.

**Comment by loliuy** [comment]
> I change also Injected.js // window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0]; window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0]; Thank You It's working.

sorry,but where is the injected.js?

**Comment by GreenerX** [comment]
> > I change also Injected.js // window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0]; window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0]; Thank You It's working.
> 
> sorry,but where is the injected.js?

node_modules/whatsapp-web.js/src/util

**Comment by RyanBrayan** [comment]
Go to the dowloadMedia function and find the following line:
const decryptedMedia = await window.Store.DownloadManager.downloadAndDecrypt

Replace with this:

const decryptedMedia = await window.Store.DownloadManager.downloadAndMaybeDecrypt

**Comment by cce15** [comment]
It works thank you all

**Comment by Sevyten** [comment]
change to in the package.json to "whatsapp-web.js": "1.21.1-alpha.1"
