### ISSUE TITLE
With each answer the bot says hello

### ISSUE THREAD

**Issue by iloukou** [askrella/whatsapp-chatgpt#150]
With each answer the bot says hello. It's as if the bot doesn't remember previous messages. the prompt sent for each message does not match the conversation history.

**Comment by ImmortalMan01** [comment]
I thought I was the only one having this problem +1

**Comment by Hasbun** [comment]
I think I've found the issue. The bot is not storing its own messages when prompting the next reply, only the user messages.
I replicated the issue in python and got similar results, but don't know how to fix it here.

If anyone knows please help! Thx

**Comment by doofzoff** [comment]
guys do have this problem when send audiofile? Error: Evaluation failed: TypeError: window.Store.DownloadManager.downloadAndDecrypt is not a function , if not what version of node.js do you use? can you tell me pls

**Comment by ImmortalMan01** [comment]
> guys do have this problem when send audiofile? Error: Evaluation failed: TypeError: window.Store.DownloadManager.downloadAndDecrypt is not a function , if not what version of node.js do you use? can you tell me pls

**Dude, I already opened a thread for this, please let's discuss it there. I found a temporary solution to it.**

**Comment by ImmortalMan01** [comment]
**The problem still persists, anyone have a solution?**

**Comment by navopw** [comment]
I cant reproduce this issue. For me the context works fine actually.
![image](https://user-images.githubusercontent.com/6507938/226169345-fae2d529-ae58-4c9f-bd41-ba139543a30b.png)

**Comment by Hasbun** [comment]
> I cant reproduce this issue. For me the context works fine actually. ![image](https://user-images.githubusercontent.com/6507938/226169345-fae2d529-ae58-4c9f-bd41-ba139543a30b.png)

It doesn't store the bot replies, but stores yours. So it doesn't know what has already asked or said. Only what you said.

**Comment by Hasbun** [comment]
updating whatsapp-web.js to 1.19.5 fixed the issue for me

**Comment by lucifer8023** [comment]
it is not work

**Comment by iloukou** [comment]
Why do you close the issue knowing that we didn’t have solutions yet.

**Comment by ignaciogomez** [comment]
Hi, I have the same issue, in all AI replies he add Hello and the previous responses, weird...
