### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by hlayiso** [askrella/whatsapp-chatgpt#154]
Can i set this up using Termux? Android

**Comment by navopw** [comment]
If you can install puppeteer and nodejs, it should work. Didn't tested it myself.

**Comment by Octotun** [comment]
When i was installing i got errors while installing Puppeteer. The problem was with chromium "snap install chromium"

**Comment by ysfcn2001** [comment]
no it's not work. You allow error by puppeteer. puppeteer is not work on androidOS
