### ISSUE TITLE
Bot stops working after some time

### ISSUE THREAD

**Issue by hlayiso** [askrella/whatsapp-chatgpt#158]
I installed and set up the bot correctly. It also works perfectly. Now I wanted to keep the bot accessible 24/7 and put it on my server. After a period of inactivity, the bot stops responding and throws an error. Does anyone have any idea how I can get around this so that I can message the bot 24/7? I'm running this on Digitalocean Droplet Debian 22

**Comment by hlayiso** [comment]
Immediately after closing my terminal it stops working

**Comment by ankitgupta89** [comment]
run it in a screen and then detach from screen before closing terminal.

**Comment by hlayiso** [comment]
How to detach? I don't know how to detach

**Comment by ankitgupta89** [comment]
to detach : 
ctrl + a + d

to reattach , first list screens
screen -ls
to attach
screen -r screenid

**Comment by ankitgupta89** [comment]
> After running "npm run start" i detach?

yes

**Comment by hlayiso** [comment]
Awesome it worked, after opening my terminal i installed `screen` then ran it after that i ran the `whatsapp-chatgpt` processes after successfully logged in message i ran `CTRL A+D`. THANKS

**Comment by hlayiso** [comment]
💯🔥💡
