### ISSUE TITLE
how to keep it running after close ssh terminal ?

### ISSUE THREAD

**Issue by jerryrat** [askrella/whatsapp-chatgpt#159]
how to keep it running after close ssh terminal ?

**Comment by hlayiso** [comment]
Use screen. To use screen start by installing it `sudo apt install screen` then run it by saying `screen` the run your processes when you done don't close the terminal, run `CTRL A+D` then you can close the terminal. It will run in the background. You can also reattach the screen by saying `screen -r`

**Comment by AlessandroAnnini** [comment]
You should use Docker or at least [PM2](https://pm2.keymetrics.io/). Install it and then from inside whatsapp-chatgpt folder

- start the process `pm2 start npm --name "whatsapp-chatgpt" -- start`
- open logs to scan QR code `pm2 log` (they update realtime so it's like watching the real process)
- then when you pulled updates from the repo or modified the conf. you can use 
- `pm2 restart whatsapp-chatgpt` or `pm2 stop all` to stop

**Comment by chuvadenovembro** [comment]
installation and suggested use of pm2

npm install -g pm2

pm2 startup

cd /root/whatsapp-chatgpt ; pm2 start npm --name "chatgpt" -- start

pm2 save

pm2 logs

**Comment by connorv001** [comment]
Or just use screen.

**Comment by navopw** [comment]
Screen or Docker is the way to go 👍
