### ISSUE TITLE
This model's maximum context length is 4097 tokens. However, you requested 4250 .....

### ISSUE THREAD

**Issue by kingofkillers91** [askrella/whatsapp-chatgpt#162]
[GPT] Received prompt from [17869360334@c.us](mailto:17869360334@c.us): hey
whatsapp-chatgpt_1 | ◇ [GPT] New conversation for [17869360334@c.us](mailto:17869360334@c.us) (ID: 55d53b60-2b31-4613-b593-890a1dcfcf55)
whatsapp-chatgpt_1 | An error occured Error: This model's maximum context length is 4097 tokens. However, you requested 4250 tokens (154 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
whatsapp-chatgpt_1 | at ChatGPT.askStream (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:152:11)
whatsapp-chatgpt_1 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
whatsapp-chatgpt_1 | at ChatGPT.ask (file:///app/node_modules/chatgpt-official/src/classes/chatgpt.ts:97:10)
whatsapp-chatgpt_1 | at Module.handleMessageGPT (/app/src/handlers/gpt.ts:63:15)
whatsapp-chatgpt_1 | at Module.handleIncomingMessage (/app/src/handlers/message.ts:143:3)
whatsapp-chatgpt_1 | at Client. (/app/src/index.ts:84:3)
I'm running the bot on docker. and i have no idea where i should edit set the max tokens cause there isn't any variable to set that in the docker-compose.yml

**Comment by law108000** [comment]
You have two options for resolving it:
- Option 1: by adding ```MAX_MODEL_TOKENS=2000``` under the environment section of your docker-compose.yml file
- Option 2: follow the [installation guide](https://askrella.github.io/whatsapp-chatgpt/#/pages/installation), to create the .env file, and retry ```docker-compose up```

**Comment by kingofkillers91** [comment]
I added the first option it's working now, thanks. But the right variable on the docker-compose.yml is  
MAX_MODEL_TOKENS: 2000

**Comment by krunchosg** [comment]
> I added the first option it's working now, thanks. But the right variable on the docker-compose.yml is MAX_MODEL_TOKENS: 2000

this didn't work for me. =(

**Comment by krunchosg** [comment]
ok. found the fix myself. i think the .eve configuration file isn't being read properly and got 'ignored'
so i went to the src/config.ts to hard-code the token limit to 2000

**Comment by belqit** [comment]
> I added the first option it's working now, thanks. But the right variable on the docker-compose.yml is MAX_MODEL_TOKENS: 2000
`MAX_MODEL_TOKENS: "2000"`
put the value as string could fix the problem

**Comment by belqit** [comment]
> > I added the first option it's working now, thanks. But the right variable on the docker-compose.yml is MAX_MODEL_TOKENS: 2000
> 
> `MAX_MODEL_TOKENS: "2000"` put the value as string could fix the problem

not true it still happens after a while, i have to restart docker container
