### ISSUE TITLE
Is it possible not to receive message replies from the number itself? (no prefix)

### ISSUE THREAD

**Issue by chuvadenovembro** [askrella/whatsapp-chatgpt#164]
I'm sending notifications to contacts with another api and whenever I send that notification, gpt responds.

I would like gpt not to answer the number itself

It's possible?

**Comment by harrison001** [comment]
You can use a filter to mark such kind of notification. in handleIncomingMessage function of [src](https://github.com/askrella/whatsapp-chatgpt/tree/master/src)/[handlers](https://github.com/askrella/whatsapp-chatgpt/tree/master/src/handlers)/message.ts
