### ISSUE TITLE
Evaluation failed when sending audio transcripted from text - it will crash 

### ISSUE THREAD

**Issue by harrison001** [askrella/whatsapp-chatgpt#166]
![Xnip2023-03-23_23-21-40](https://user-images.githubusercontent.com/2585897/227442008-b728c9e8-f72d-482f-ba4b-59acbd02d7e7.jpg)

The key settings are the followings.
TTS_ENABLED=true
TTS_MODE=speech-api

The event occurred randomly, and I divided the text into 200-character segments (the audio should be small enough) to ensure it wouldn't be excessively long. 

I suspect it is related to whatsapp-web.js as this bug occurs without a discernible pattern.

**Comment by connorv001** [comment]
Try updating to latest version

**Comment by harrison001** [comment]
Got it. Thank you!

**Comment by harrison001** [comment]
Did not crash again so far. Thank you again.

**Comment by siisee11** [comment]
Still have this problem.
