### ISSUE TITLE
Just use transcription

### ISSUE THREAD

**Issue by 1letzgo** [askrella/whatsapp-chatgpt#167]
It's possible that the bot just transcribe the Voice message and did not answer?

**Comment by connorv001** [comment]
Please provide further clarification

**Comment by 1letzgo** [comment]
I need only the transcription of the voice message. And the summary. No response from gpt.

Get a lot of voicemails daily but can't always hear them due to health reasons.

**Comment by steve-hb** [comment]
Should only need small changes in the configuration logic. If someone is interested: we're open for contributions! :)

**Comment by cristigoia** [comment]
To stop replying to your transcript, you can simply just comment the `line 107` `// await handleMessageGPT(message, transcribedText);` in `src/handlers/message.ts` 😄
