### ISSUE TITLE
Failed to load url qrcode-terminal

### ISSUE THREAD

**Issue by seynisch** [askrella/whatsapp-chatgpt#174]
I run into these errors:

```
Failed to load url qrcode-terminal (resolved id: qrcode-terminal) in /root/whatsapp-chatgpt/src/index.ts. Does the file exist?
Failed to load url whatsapp-web.js (resolved id: whatsapp-web.js) in /root/whatsapp-chatgpt/src/index.ts. Does the file exist?
file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-79892de8.js:41096
        const err = new Error(`Failed to load url ${url} (resolved id: ${id})${importer ? ` in ${importer}` : ''}. ${msg}`);
                    ^

Error: Failed to load url qrcode-terminal (resolved id: qrcode-terminal) in /root/whatsapp-chatgpt/src/index.ts. Does the file exist?
    at loadAndTransform (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-79892de8.js:41096:21) {
  code: 'ERR_LOAD_URL'
```

Can someone tell me how to solve this?

I did exactly those steps: https://askrella.github.io/whatsapp-chatgpt/#/pages/installation

**Comment by jano01-sudo** [comment]
i have the same

**Comment by Mo-GH** [comment]
also the same problem

**Comment by devadarshan5** [comment]
#174
![image_2023-04-28_073446599](https://user-images.githubusercontent.com/99719563/235036863-a42f2613-52fb-49a7-bc8a-d5c485a2827d.png)
I got this while running npm run start

**Comment by devadarshan5** [comment]
> Try : npm install qrcode-terminal

Tried it but it doesn't fix the issue

**Comment by IamZiroToxic** [comment]
Use `npm start`

**Comment by RKP64** [comment]
![Screenshot (28)](https://github.com/askrella/whatsapp-chatgpt/assets/121541878/51c91d5a-8e2f-4312-a3c8-44d55d626171)
 need 
![Screenshot (28)](https://github.com/askrella/whatsapp-chatgpt/assets/121541878/2caf8085-eb12-4670-970e-6cf09ff840e3)
 please solve this its a library issue i think

**Comment by chowyik** [comment]
I have exactly same problem 

> ![Screenshot (28)](https://user-images.githubusercontent.com/121541878/252137563-51c91d5a-8e2f-4312-a3c8-44d55d626171.png) need ![Screenshot (28)](https://user-images.githubusercontent.com/121541878/252137600-2caf8085-eb12-4670-970e-6cf09ff840e3.png) please solve this its a library issue i think

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
