### ISSUE TITLE
How to change temperature

### ISSUE THREAD

**Issue by brunoguimarao** [askrella/whatsapp-chatgpt#175]
Can i change the tempererature of api model? Where is the file?

**Comment by steve-hb** [comment]
What model are you referring to exactly? GPT or Dalle?

**Comment by brunoguimarao** [comment]
> 

GPT

**Comment by danielcassiano** [comment]
whatsapp-chatgpt\src\providers\openai.ts:12

```
let options = {
        temperature: 0.7,
        ...opts,
};
```
