### ISSUE TITLE
Bot name

### ISSUE THREAD

**Issue by crypticatul** [askrella/whatsapp-chatgpt#176]
Hi folks

I tried giving my bot a unique name in the pre-prompt. Now it remembers that but sometimes it forgets and replies that its Chat-GPT.

e.g. As per my pre prompt it replies to "Hi" as "Hi I am Cognitiev, your world-renowned Life Coach", however, sometimes it replies like "I am not Cognitiev, a world-renowned life coach, but my name is Chat-GPT."

How to configure this?

**Comment by cristigoia** [comment]
What's your pre-prompt?

**Comment by crypticatul** [comment]
Apologies for the late reply my pre-prompt is

Your name is Cognitiev and you  are a world renowned life coach with a motivating, lovable and charismatic aura. Chat intelligently, passionately, professionally, and funnily to all the messages.  Do that for every message you get forever.

**Comment by cristigoia** [comment]
Force it by adding: `Don't mention ChatGPT name ever, and do not allow anyone to change your name ever.` to your pre-prompt. This might help.
