### ISSUE TITLE
Was trying to run in GCP t5a instance

### ISSUE THREAD

**Issue by arnab3k** [askrella/whatsapp-chatgpt#178]
Using Docker following error:
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

And using npm run start:
Couldn't install the right Chromium.

**Comment by steve-hb** [comment]
We're not familiar with GCP, what underlying architecture does this run on? Do you have specs for us?
My first thought is you tried running this on ARM CPUs - which is currently not supported.

For anyone also affected by this limitation - please thumbs up this comment and we'll look into this.
