### ISSUE TITLE
[Enhancement] Adding Microsoft Playwright as an alternative library to Puppeteer

### ISSUE THREAD

**Issue by ElliotBadinger** [askrella/whatsapp-chatgpt#179]
Would it be possible for you to add Playwright compatibility should the platform a user is using not be compatible with Puppeteer like for instance when using Termux on Android, Puppeteer is incompatible with Android devices but Playwright is* (with a little tweaking).

*When installing ubuntu through the use of the F-droid app AnLinux and installimg it from that OS.

**Comment by navopw** [comment]
You have to open this issue on whatsapp web js repo, not our stuff
