### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by aleemb** [askrella/whatsapp-chatgpt#184]
I can interface with ChatGPT via https://chat.openai.com/chat but not via this install which constantly gives the error: `Request failed with status code 429`.

**Comment by aleemb** [comment]
FWIW, upgrading to premium didn't help either.

**Comment by frappierer** [comment]
same here.

**Comment by navopw** [comment]
https://help.openai.com/en/articles/5955604-how-can-i-solve-429-too-many-requests-errors

**Comment by frappierer** [comment]
I solved it by paying for the api. @aleemb it’s not enough to pay for gpt (the chat). You have to add payment info here: https://platform.openai.com/account/billing/payment-methods

did you do that?

**Comment by jm-rizkallah** [comment]
@frappierer this is what i have

![image](https://user-images.githubusercontent.com/92910078/231487419-fccc41ef-0168-4661-a3d9-366a286055df.png)

**Comment by frappierer** [comment]
You are still in the free tier. 
it seems you’re paying for the chat, but not for open AI.

**Comment by aleemb** [comment]
Paying for the API fixed it, thanks!
