### ISSUE TITLE
History for each chat

### ISSUE THREAD

**Issue by frappierer** [askrella/whatsapp-chatgpt#185]
I have two chats.

Chat 1: !gpt what is 1+1? -> I will get the correct answer.
Chat 2:!gpt what was my last question -> It will tell me "what is 1+1". I would have expected "You did not ask anything yet"

It would be great if the history is for one chat and not globally.

Alternatively. is there a way of resetting it (sure you can prompt that by "!gpt forget everything until now"I?

**Comment by cristigoia** [comment]
The history should be per user, right? (please clarify the question if I got it wrong) You can reset the conversation by typing `!reset` (executing `delete conversations[message.from]`)

**Comment by cristigoia** [comment]
As I understand, each conversation window is in fact a new conversation - so each chat is a separate chat.

But to make sure I understand. If you say, in one chat, something like `!gpt Please summarize our conversation so far`, it will return a summary from other chats as well?

**Comment by frappierer** [comment]
Exactly

**Comment by mrahmadt** [comment]
Hi Team

So to clarify, is whatsapp-chatgpt memory by user or by chat window?

it make more sense to be by chat window

**Comment by navopw** [comment]
By user
