### ISSUE TITLE
I couldn't understand what you said as reply on every voice memo

### ISSUE THREAD

**Issue by lucasvr23** [askrella/whatsapp-chatgpt#186]
Did two installs on different instances, but whatever I say it's giving me this reply. Transription mode is set to openai and use transcription set to true.

**Comment by krunchosg** [comment]
I'm using the same settings and facing the same issue. 
below is the Json response. Any idea how to fix it?
{
  [Symbol(realm)]: null,
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: true,
    requestIncludesCredentials: true,
    type: 'default',
    status: 400,
    timingInfo: {
      startTime: 191410.17090001702,
      redirectStartTime: 0,
      redirectEndTime: 0,
      postRedirectStartTime: 191410.17090001702,
      finalServiceWorkerStartTime: 0,
      finalNetworkResponseStartTime: 0,
      finalNetworkRequestStartTime: 0,
      endTime: 0,
      encodedBodySize: 224,
      decodedBodySize: 224,
      finalConnectionTimingInfo: null
    },
    cacheState: '',
    statusText: 'Bad Request',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    body: { stream: undefined }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(16) {
      'date' => [Object],
      'content-type' => [Object],
      'content-length' => [Object],
      'connection' => [Object],
      'openai-organization' => [Object],
      'openai-processing-ms' => [Object],
      'openai-version' => [Object],
      'strict-transport-security' => [Object],
      'x-ratelimit-limit-requests' => [Object],
      'x-ratelimit-remaining-requests' => [Object],
      'x-ratelimit-reset-requests' => [Object],
      'x-request-id' => [Object],
      'cf-cache-status' => [Object],
      'server' => [Object],
      'cf-ray' => [Object],
      'alt-svc' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}

**Comment by BrainMotto** [comment]
Same thing here when using transcription. Using on docker headless on raspberry pi 3b (latest bullseye). Works perfectly on MacOS.

`Response {
  [Symbol(realm)]: null,
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: true,
    requestIncludesCredentials: true,
    type: 'default',
    status: 400,
    timingInfo: {
      startTime: 569313.90615201,
      redirectStartTime: 0,
      redirectEndTime: 0,
      postRedirectStartTime: 569313.90615201,
      finalServiceWorkerStartTime: 0,
      finalNetworkResponseStartTime: 0,
      finalNetworkRequestStartTime: 0,
      endTime: 0,
      encodedBodySize: 227,
      decodedBodySize: 227,
      finalConnectionTimingInfo: null
    },
    cacheState: '',
    statusText: 'Bad Request',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    body: { stream: undefined }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(16) {
      'date' => [Object],
      'content-type' => [Object],
      'content-length' => [Object],
      'connection' => [Object],
      'openai-organization' => [Object],
      'openai-processing-ms' => [Object],
      'openai-version' => [Object],
      'strict-transport-security' => [Object],
      'x-ratelimit-limit-requests' => [Object],
      'x-ratelimit-remaining-requests' => [Object],
      'x-ratelimit-reset-requests' => [Object],
      'x-request-id' => [Object],
      'cf-cache-status' => [Object],
      'server' => [Object],
      'cf-ray' => [Object],
      'alt-svc' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}`

**Comment by envieme** [comment]
Same issue here. Not sure why openAI is returning bad request?

**Comment by krunchosg** [comment]
anyone has a workaround? it's been so many days since it's brought up here .. =X

**Comment by BrainMotto** [comment]
I had to rewrite all the code that do the transcription (transcribeOpenAI) to the official way by the documentation using the OpenAI API Keys, when using OpenAI's whisper. Then it worked. For sure someone can rework the code to be optimal but I can share here...

Couldn't find a way to reuse the 'openai' instance to inside the transcribeOpenAI function, so I redeclared as 'open_ai'... Maybe someone can help improve the code and make a pull request.
In /src/providers/openai.ts update the transcribeOpenAI function like the code bellow:


```
export async function transcribeOpenAI(audioBuffer: Buffer): Promise<{ text: string; language: string }> {

	const url = config.openAIServerUrl;
	let language = "";

	const tempdir = os.tmpdir();
	const oggPath = path.join(tempdir, randomUUID() + ".ogg");
	const wavFilename = randomUUID() + ".wav";
	const wavPath = path.join(tempdir, wavFilename);
	fs.writeFileSync(oggPath, audioBuffer);
	try {
		await convertOggToWav(oggPath, wavPath);
	} catch (e) {
		fs.unlinkSync(oggPath);
		// error logging
		console.error(`Could not convert to wav. ${e}`);
		return {
			text: "",
			language
		};
	}

	const { Configuration, OpenAIApi } = require("openai");
	const configuration = new Configuration({
	apiKey: config.openAIAPIKey,
	});
	const open_ai = new OpenAIApi(configuration);

	let response;
	try {
		console.log(wavPath);
		response = await open_ai.createTranscription(
			fs.createReadStream(wavPath),
			"whisper-1"
			);
	} catch (e) {
		console.error(e);
	} finally {
		fs.unlinkSync(oggPath);
		fs.unlinkSync(wavPath);
	}

	if (!response || response.status != 200) {
		console.error(response);
		return {
			text: "",
			language: language
		};
	}
	console.log(response.data.text);
	// const transcription = await response.json();
	return {
		text: response.data.text,
		language
	};
}
```

Best Regards,
Sandro Akira

**Comment by envieme** [comment]
Great this works. What changes did you do?

**Comment by navopw** [comment]
Thank you for sharing, when I have time I will add this into the repo...

**Comment by krunchosg** [comment]
> createTranscription

hi, i tried your code. but i'm getting the following error. Any resolution?
TypeError: open_ai.createTranscription is not a function
    at Module.transcribeOpenAI (C:\Users\krunc\whatsapp-chatgpt\src\providers\openai.ts:66:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Module.handleIncomingMessage (C:\Users\krunc\whatsapp-chatgpt\src\handlers\message.ts:56:15)
    at Client.<anonymous> (C:\Users\krunc\whatsapp-chatgpt\src\index.ts:57:5)
undefined
node:events:491
      throw er; // Unhandled 'error' event

**Comment by BrainMotto** [comment]
My guess is that probably your openai version is old. Try updating it to 3.2.1 in package.json.

**Comment by epetros** [comment]
**_sudo apt-get install ffmpeg_** fixed the issue for me has suggested by [this comment in discord](https://discord.com/channels/1076823522128699422/1076823706355105833/1091718571098378350)
