### ISSUE TITLE
offer a totally free Text To speech, edge and google

### ISSUE THREAD

**Issue by joe12801** [askrella/whatsapp-chatgpt#188]
dont need to pay,all is free,you can access to this project
https://github.com/rany2/edge-tts
https://github.com/pndurette/gTTS

**Comment by joe12801** [comment]
dont need to pay,all is free,you can access to this project
https://github.com/rany2/edge-tts
https://github.com/pndurette/gTTS

**Comment by Ichtestenurmal** [comment]
any tutorial how to use it?
