### ISSUE TITLE
Eror code 429

### ISSUE THREAD

**Issue by FahmiDR** [askrella/whatsapp-chatgpt#189]
Request Failed with Status Code 429
<img width="182" alt="image" src="https://user-images.githubusercontent.com/67456769/231688662-6af42777-3f90-42bf-9ae4-1fd8025cab75.png">

**Comment by AbdulrahmanQu** [comment]
any updates for resolving this issue ?

**Comment by cristigoia** [comment]
`Error Code 429 - Rate limit reached for requests | OpenAI Help Center. This error message indicates that you have hit your assigned rate limit for the API. This means that you have submitted too many tokens or requests in a short period of time and have exceeded the number of requests allowed.` - read more [here](https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests)

**Comment by adamshand** [comment]
This is an error from OpenAI, check your billing status.  I'd hit my hard quota and needed to increase it.
