### ISSUE TITLE
Stress testing for a large deployment

### ISSUE THREAD

**Issue by envieme** [askrella/whatsapp-chatgpt#193]
I am wondering how many users and sessions can it support at a time? How many messages incoming can it handle given a set of resources it runs on?

**Comment by Ease78** [comment]
Seconded. I'll do a test on a 40ish users and report back, but need to know its reliability for 1000's of users.

**Comment by envieme** [comment]
Could you run this test? May I know how you managed it and if it worked for a lot of requests at a time?

**Comment by Ease78** [comment]
> Could you run this test? May I know how you managed it and if it worked for a lot of requests at a time?

Hi there. I just finished a test and after a week, it is still standing strong. I estimate around a 100ish searches, from 20ish people. I never got rate-limited. But IDK how to find more people to test this for 1000's of users.

So it's good enough but I do not know how good it is.

**Comment by Re1da** [comment]
> > Could you run this test? May I know how you managed it and if it worked for a lot of requests at a time?
> 
> Hi there. I just finished a test and after a week, it is still standing strong. I estimate around a 100ish searches, from 20ish people. I never got rate-limited. But IDK how to find more people to test this for 1000's of users.
> 
> So it's good enough but I do not know how good it is.
