### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by Ichtestenurmal** [askrella/whatsapp-chatgpt#194]
◇  [GPT] Received prompt from 4917620126250@c.us: say hello in a nice way
◇  [MODERATION] Checking user prompt...

Why does this happen

**Comment by jm-rizkallah** [comment]
Using docker compose or normal installation?

**Comment by joe-karaki** [comment]
Normal installation

**Comment by Dagolin** [comment]
Same here

**Comment by navopw** [comment]
Engine Exiting Issue When Deleting Messages
