### ISSUE TITLE
3.5 or 4 not active

### ISSUE THREAD

**Issue by Aj-Butt** [askrella/whatsapp-chatgpt#195]
GPT Model (default: gpt-3.5-turbo) or GPT-4

doesnt matter which 1 is selected in .env or mention its working on GPT-3 model

am i doing something wrong or missing some other settings

**Comment by dallonasnes** [comment]
i'm also seeing a 404 those two models.

**Comment by sudanime** [comment]
I have the same issue GPT-4 showing 404 issue
