### ISSUE TITLE
Audio and text message response at the same time

### ISSUE THREAD

**Issue by juliandaz11** [askrella/whatsapp-chatgpt#200]
I would like the bot to reply to the text message together with the audio. That I would have to modify to achieve it. Thanks a lot

**Comment by connorv001** [comment]
Haven't implemeted that yet, may work on it soon

**Comment by juliandaz11** [comment]
already done [https://github.com/juliandaz11/whatsapp-chatgpt/commit/74b38695047d9159a52c16a5e156ea722f114919?diff=split](url)

**Comment by juliandaz11** [comment]
#210
