### ISSUE TITLE
Integration with stable diffusion

### ISSUE THREAD

**Issue by juliandaz11** [askrella/whatsapp-chatgpt#203]
It would be good to integrate with stable diffusion webui, or connect with the huggingfac api

**Comment by Seitk** [comment]
Added here, will fire a PR soon
https://github.com/Seitk/whatsapp-chatgpt/pull/3

**Comment by Seitk** [comment]
https://github.com/askrella/whatsapp-chatgpt/pull/207

**Comment by renancunhasousa** [comment]
const handleMessageStableDiffusion = async (client: any, message: any, prompt: string, userConfig: IConfig  ) => {
	try {
		const start = Date.now();
		cli.print(`[Stable Diffusion] Received prompt from ${message.from}: ${prompt}`);
		client.sendMessage(message.from, '⏳ _loading..._')

		// Verificação e moderação do prompt
		if (userConfig.promptModerationEnabled) {
		  try {
			await moderateIncomingPrompt(prompt, userConfig);
		  } catch (error: any) {
			message.reply(error.message);
			return;
		  }
		}
	
		// Autenticação e inicialização do cliente Replicate
		const token = userConfig.replicateAPI || process.env.REPLICATE_API_TOKEN;
		if (!token || typeof token !== "string") {
		  throw new Error("REPLICATE_API_TOKEN não está definido.");
		}
		const replicate = new Replicate({ auth: token });
	
		// Execução do modelo
		const response = await replicate.run(
		  "stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",
		  { input: { prompt: prompt } }
		);
	
		const end = Date.now() - start;
	
		const imageURI = response[0] as string;
		const imageResponse = await fetch(imageURI);
		const arrayBuffer = await imageResponse.arrayBuffer();
		const imageBuffer = Buffer.from(arrayBuffer);
		const image = new MessageMedia("image/jpeg", imageBuffer.toString("base64"), "image.jpg");


		
	
		cli.print(`[Stable Diffusion] Answer to ${message.from} | Replicate request took ${end}ms`);
	
		const caption = {
			caption: '```by 🖼 Stable Diffusion```',
		  };
		client.sendMessage(message.from, image, caption);

	  } catch (error: any) {
		console.error("An error occurred", error);
		message.reply(
		  "*Um erro ocorreu/An error occured*\n\n💬 _Aguarde um pouco e tente novamente_\n\n💬 _Please wait a little while and try again_\n\n\t (" + error.message + ")"
		);
	  }
	};

**Comment by navopw** [comment]
I just merged the PR, so !sd will be available :)

Big thanks to @Seitk

**Comment by juliandaz11** [comment]
@Seitk Thanks man very nice
