### ISSUE TITLE
[Langchain] Add memory and custom prompt to Langchain agent

### ISSUE THREAD

**Issue by iloukou** [askrella/whatsapp-chatgpt#208]
I tried to implement Langchain agent with memory and custom prompt. It works but still not have memory. The agent does not remember the last conversation message. Excuse my bad english, my natural language is french. Thks to give help .
import { BufferMemory } from "langchain/memory";
import { ConversationChain } from "langchain/chains";
import { OpenAI } from "langchain/llms/openai";
import { SerpAPI } from "langchain/tools";
import { LLMChain } from "langchain/chains";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { ZeroShotAgent, AgentExecutor } from "langchain/agents";
import {
  ChatPromptTemplate,
  SystemMessagePromptTemplate,
  HumanMessagePromptTemplate,
  MessagesPlaceholder
} from "langchain/prompts";
import * as cli from "../cli/ui"; 
export default class BrowserAgentProvider {
  

  tools = [
    new SerpAPI()
    // new RequestsGetTool(),
  ];

  //model = new OpenAI({ temperature: 0 });

  fetch = async (query) => {
      
    const chat = new OpenAI({modelName: "gpt-4", temperature: 0});
    //const memory = new BufferMemory({ returnMessages: true, memoryKey : "history" });
    const prefix = `Answer the following questions as best you can, but speaking as a pirate might speak. You have access to the following tools:`;
    const suffix = `Begin! Remember to speak as a pirate in french when giving your final answer. Use lots of "Args" .
        {chat_history}
        Question:  {input}
        {agent_scratchpad}`;

    const createPromptArgs = {
        suffix,
        prefix,
        inputVariables: ["input", "agent_scratchpad", "chat_history"],
    };
    const memory1 = new BufferMemory({ memoryKey : "chat_history", inputKey: "input", outputKey:"output" });
    const prompt = ZeroShotAgent.createPrompt(this.tools, createPromptArgs);

    const llmChain = new ConversationChain({prompt: prompt,llm: chat,memory: memory1 });

    const agent = new ZeroShotAgent({
      llmChain,
      allowedTools: this.tools.map((tool) => tool.name),
      verbose: true,
    });

    

    
    
    
    //const executor = AgentExecutor.fromAgentAndTools({ agent, tools: this.tools });
    
    const executor = AgentExecutor.fromAgentAndTools({agent: agent, tools: this.tools, verbose:true,memory: memory1});

    const response = await executor.run({ input: query });
cli.print(`[Prompt LANG] voici le plan ${prompt}`);

    return response.output;
  };
}

**Comment by bfpill** [comment]
Try passing `input_variables=["input", "chat_history", "agent_scratchpad"]` to the createPrompt function:

const prompt = ZeroShotAgent.createPrompt(this.tools, createPromptArgs, input_variables:["input", "chat_history", "agent_scratchpad"]);

Hopefully that works for you : )
