### ISSUE TITLE
Ignoring message because it is not whitelisted

### ISSUE THREAD

**Issue by shahzaib-111** [askrella/whatsapp-chatgpt#212]
![Error](https://user-images.githubusercontent.com/132267617/235446981-d7d4dc53-2ff3-45ce-b71f-58527d6c425e.png)
Dear expert please guide me. When i try to message to the chatbot it ignore the message and message come direct into the inbox. No response from the chatbot it shows that ignoring message because it is not whitelisted. I also try to whitelist the number by using command !config general whitelists 92300043.... it show that it updated but i try to send message it shows the same issue. Please let me know how to whitelist the number. Thank you.

**Comment by ArbazYousuf** [comment]
@shahzaib-111  try to message your own number. then set  "!config general whitelist <value>"

**Comment by shahzaib-111** [comment]
@ArbazYousuf bro i send it from own number but failed.

**Comment by shahzaib-111** [comment]
@ArbazYousuf It says updated but dont work. I just wonder how to whitelist the number i.e i send from my number like "!config general whitelist 9230004321** " it shows me on my number that it updated successfully but did not respond from chatgpt and on terminal show same message it ignore because it is not whitelisted.

**Comment by sudanime** [comment]
I'm facing same issue , when I whatsapp my same number its working fine but when messaging from other numbers its not working Ignoring message from 966500******@c.us because it is not whitelisted.

**Comment by sudanime** [comment]
issue is solved im my side 
im using this configuration 
`# Whether or not to use prefixes !gpt and !dalle
PREFIX_ENABLED=false

# Whether or not to use prefixes for self-note conversation
PREFIX_SKIPPED_FOR_ME=false

# Set own prefixes for ChatGPT, DALL-E, reset context, configuration
GPT_PREFIX=
DALLE_PREFIX=imagine
RESET_PREFIX=!reset
AI_CONFIG_PREFIX=!confi`

`# Access control, only allow whatsapp-chatgpt to react to specific phone numbers, comma-separated
WHITELISTED_PHONE_NUMBERS=9665****@c.us,96650****@c.us,880*****@c.us`

**Comment by jerryrat** [comment]
#WHITELISTED_PHONE_NUMBERS

**Comment by aamirswati** [comment]
Delete "#WHITELISTED_PHONE_NUMBERS" from .env file to response to everyone message. Otherwise you can add a specific number as whitelist.
If you enable "PREFIX_ENABLED=true" remember to put prefix i-e !gpt or !dalle before every prompt.
Good luck.

**Comment by Re1da** [comment]
> @shahzaib-111 try to message your own number. then set "!config general whitelist "

**Comment by ysfcn2001** [comment]
> > @shahzaib-111 try to message your own number. then set "!config general whitelist "

it's not working man else solition
