### ISSUE TITLE
[WARN] Importing from 'langchain/llms'

### ISSUE THREAD

**Issue by samlyn26** [askrella/whatsapp-chatgpt#222]
tried to fix this error but nothing i tried worked ! help please
whaatever message i send it shows 
[AI-Config] Initialized AI config
◇  Ignoring old message: Hi

the log is
(node:26972) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[WARN] Importing from 'langchain/llms' is deprecated. Import from eg. 'langchain/llms/openai' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.

**Comment by marcusabu** [comment]
It's just a warning, the app continues to run.

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
