### ISSUE TITLE
Whether check & help "Request failed with status code 429"

### ISSUE THREAD

**Issue by Yogasastha** [askrella/whatsapp-chatgpt#225]
Dear Support Team,

I am writing to report an issue that I have been experiencing while using your service. Whenever I try to access the service, I receive an error message that says "Request failed with status code 429." This error has been occurring consistently for the past few days, and it has been preventing me from using the service effectively.

I would appreciate it if you could look into this issue and provide a solution as soon as possible. I understand that a status code of 429 indicates that I am making too many requests in a given time frame, but I have not been intentionally overloading the system. I have checked my request frequency and it seems to be within the limits set by your service.

I would appreciate any assistance you can provide in resolving this issue. Thank you in advance for your attention to this matter.

**Comment by maidmus** [comment]
Paid Openai Account? Limit not reached?

**Comment by Yogasastha** [comment]
> Paid Openai Account? Limit not reached?

I'm not paid to Openai account.but it is free only,that reason I used this code.It shows rate limit is reached (request failed with status code 429)

**Comment by Yogasastha** [comment]
> Paid Openai Account? Limit not reached?

Please give your contact number or I'd to discuss about the project with ur opinion

**Comment by maidmus** [comment]
Just sign up for paid api and set rhe limit to 1 $ and try it out. It will work.
