### ISSUE TITLE
the answer is only appearing in the console

### ISSUE THREAD

**Issue by helviodarochalima** [askrella/whatsapp-chatgpt#229]
the answer is only appearing on the console, on the cell phone (ios) there is no answer to the prompt. what do you need to configure?

AbsAbs

[AI-Config] Initialized AI config
[AI-Config] Received prompt from 556181050xxx
![WhatsApp Image 2023-05-19 at 17 31 14](https://github.com/askrella/whatsapp-chatgpt/assets/70584092/0095858b-a43b-4c62-aac7-8e279cf0614c)
@c.us: 
◇  [GPT] Received prompt from 556181050xxx@c.us:  boa tarde
◇  [MODERATION] Checking user prompt...
◇  [MODERATION] OpenAI Moderation response: ["sexual: false","hate: false","violence: false","self-harm: false","sexual/minors: false","hate/threatening: false","violence/graphic: false"]
◇  [GPT] New conversation for 55618105xxx@c.us (ID: 5b3fb930-a704-4267-b8a1-c847c5ab7fb4)
◇  [GPT] Answer to 556181050xxx@c.us: Boa tarde! Como posso ajudar?  | OpenAI request took 1682ms)

**Comment by badermq76** [comment]
same issue here

**Comment by helviodarochalima** [comment]
to solve this problem you can change Message.js by inserting the following code to replace what is giving error:

if (typeof data.id.id === 'string') {
     this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
} else {
     // handle the case when data.id.id is not a string
     // for example, assign a default value
     this.deviceType = 'unknown';
}
  in the console message you have the directory where the file is...

In my case, the problem that is happening is that the OpenAI response does not return to the cell phone screen .. it is only on the console. Do you have any idea what it could be?

Abs

**Comment by badermq76** [comment]
no,

I have the same issue as you, i can see the answer on the console only. nothing received on the phone.

note: I am using docker.

**Comment by ariltonJaguilar** [comment]
Same problem here. It was working yesterday

**Comment by someoneise** [comment]
I can confirm I just cloned the new release from a week ago, and this problem is appearing. 
I used to run a different version from a month ago and it worked fine on my system. 
It seems that the last changes to the source code caused this issue.

**Comment by someoneise** [comment]
> I can confirm I just cloned the new release from a week ago, and this problem is appearing. I used to run a different version from a month ago and it worked fine on my system. It seems that the last changes to the source code caused this issue.

I correct myself: I cloned the repository on march 13th, and confirmed it ran well.
I wanted to change the number registered to the chatbot, and so i did a full reinstall, and now the bot doesnt work for the aforementioned reason: error at line 91, in Message.js

**Comment by someoneise** [comment]
by hardcoding this.deviceType to a string (like 'web'), the error is avoided and no exception is made, but the message is just not sent.

**Comment by renancunhasousa** [comment]
Solution here

https://github.com/pedroslopez/whatsapp-web.js/pull/2196/files

**Comment by helviodarochalima** [comment]
Great Job ! Works for me too !

**Comment by ShivamB25** [comment]
this isn't permanent solution. keep it open @helviodarochalima

**Comment by ShivamB25** [comment]
@navopw please look
