### ISSUE TITLE
How to keep the session active on the server

### ISSUE THREAD

**Issue by helviodarochalima** [askrella/whatsapp-chatgpt#230]
Good morning,
   
    Excuse me if I ask a primary question (I'm a beginner in this beautiful universe of containers) .. I uploaded the app to a machine on aws but I have a doubt .. how do I keep the docker session even when I turn off the notebook?

    Thank you in advance

**Comment by EdEngineering** [comment]
Hello @helviodarochalima maybe if you are using docker-compose, or just docker try using the -d flag, so the container will start in detach mode!

```bash
docker run -d --name container_name container_image
```

Then to see the logs of your container you can use, so you can see the QR code to login to your whatsapp session!

```bash
docker logs -f container_name
```
The f flag means follow so your logs will be outputed on your terminal. You can just ctrl+c afterwards!
Hope it helps!

**Comment by helviodarochalima** [comment]
Thank very much for your help.

Helvio

**Comment by envieme** [comment]
Use pm2 if you do not want Docker

**Comment by helviodarochalima** [comment]
> Use pm2 if you do not want Docker

thank you for your suggestion. i have a doubt ... which script i must use ... i tried "pm2 start src/index.ts" but it doesn't work 

Tnaks

**Comment by helviodarochalima** [comment]
I found the correct command to start the app in background mode using Pm2 ..

pm2 start npm -name "name-app" --run start

thanks
