### ISSUE TITLE
Error: TypeError: data.id.id.substring is not a function

### ISSUE THREAD

**Issue by maidmus** [askrella/whatsapp-chatgpt#236]
Hallo,

this was working fine for monts, but now im getting this error.  Im using the newest version on Node.js v18.16.0

![gpt](https://github.com/askrella/whatsapp-chatgpt/assets/115721098/5d89528f-751e-4e2c-b9e9-0ed082c0e726)

**Comment by Mr-Nobody1** [comment]
update the `"whatsapp-web.js": "^1.20.0"`

**Comment by rikuddo91** [comment]
> 

I replaced the files from the whatapp-web git repo, it doesn't crash the console now, and I do get the answer, but it doesn't post the answer in whatsapp.
How can I resolve that problem?

**Comment by emrekaramannnn** [comment]
I am getting the same error. where can I find the current version of the "whatsapp-web.js" file.

**Comment by Mr-Nobody1** [comment]
go to `Package.json` and update the version of whatsapp-web.js

**Comment by emrekaramannnn** [comment]
> 

C:\test5\node_modules\whatsapp-web.js

I am in this directory but which file to update and with what?

**Comment by emrekaramannnn** [comment]
{
	"name": "whatsapp-chatgpt",
	"version": "1.20.0",
	"description": "Whatsapp bot that uses OpenAI's GPT & DALLE to respond to user inputs",

**Comment by emrekaramannnn** [comment]
> go to `Package.json` and update the version of whatsapp-web.js

	"dependencies": {
		"@clack/prompts": "^0.4.3",
		"chatgpt-official": "^1.1.5",
		"dotenv": "^16.0.3",
		"fetch-blob": "^3.2.0",
		"ffmpeg": "^0.0.4",
		"langchain": "^0.0.62",
		"openai": "^3.1.0",
		"picocolors": "^1.0.0",
		"qrcode-terminal": "^0.12.0",
		**"whatsapp-web.js": "^1.20.0",**
		"aws-sdk": "^2.1332.0"
	},

I updated but it didn't fix it...

**Comment by Mr-Nobody1** [comment]
> > go to `Package.json` and update the version of whatsapp-web.js
> 
> ```
> 	"whatsapp-web.js": "^1.20.0",
> ```
> 
> Mr-Nobody1, thanks.
> 
> Another question..
> 
> HUGGINGFACE_API_TOKEN= What does this api key other than openai do and where is it gotten from?

I think this belongs to some models other than chatgpt like vicuna, wizardLM etc

**Comment by helviodarochalima** [comment]
Even after altering the package.json and updating whatsapp-web.js, I'm still receiving the error


r de todos os envolvidos.  | OpenAI request took 96378ms)
whatsapp_bot  | /app/node_modules/whatsapp-web.js/src/structures/Message.js:91
whatsapp_bot  |         this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
whatsapp_bot  |                                                                           ^
whatsapp_bot  | 
whatsapp_bot  | TypeError: data.id.id.substring is not a function
whatsapp_bot  |     at Message._patch (/app/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
whatsapp_bot  |     at new Message (/app/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
whatsapp_bot  |     at Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:699:16)
whatsapp_bot  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
whatsapp_bot  | 
whatsapp_bot  | Node.js v20.2.0
whatsapp_bot exited with code 1

**Comment by emrekaramannnn** [comment]
> update the `"whatsapp-web.js": "^1.20.0"`

Hello Mr-Nobody1,

Another issue occurred. Can you help me?

[](https://github.com/askrella/whatsapp-chatgpt/issues/247)

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
