### ISSUE TITLE
The audio transcription has stopped working

### ISSUE THREAD

**Issue by jmora0** [askrella/whatsapp-chatgpt#238]
The audio transcription has stopped working. It was working a few days ago, but now it doesn't show any errors, it just responds like this.

<img width="337" alt="Captura de pantalla 2023-05-22 a las 17 26 23" src="https://github.com/askrella/whatsapp-chatgpt/assets/62778323/2b0dffb3-adee-4915-a73d-57f2f9184395">
<img width="563" alt="Captura de pantalla 2023-05-22 a las 17 26 15" src="https://github.com/askrella/whatsapp-chatgpt/assets/62778323/fd44faa7-d212-476b-b41b-53fcfe057b1f">

**Comment by uphiago** [comment]
have the same problem
