### ISSUE TITLE
TypeError: data.id.id.substring is not a function - Docker

### ISSUE THREAD

**Issue by helviodarochalima** [askrella/whatsapp-chatgpt#239]
Dear friends,

    Dear friends,

    when running in docker I am getting the error below.

    Additional question, does docker "see" the settings in the .env file or do I need to copy them to another specific dockr file?

   Thank you in advance,

   Helvio

----
ontainer whatsapp_bot  Created                                                                  0.0s 
Attaching to whatsapp_bot
whatsapp_bot  | 
whatsapp_bot  | > whatsapp-chatgpt@1.0.0 start
whatsapp_bot  | > npx vite-node src/index.ts
whatsapp_bot  | 
whatsapp_bot  | (node:30) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
whatsapp_bot  | 
whatsapp_bot  | Please migrate your code to use AWS SDK for JavaScript (v3).
whatsapp_bot  | For more information, check the migration guide at https://a.co/7PzMCcy
whatsapp_bot  | (Use `node --trace-warnings ...` to show where the warning was created)
whatsapp_bot  | [WARN] Importing from 'langchain/llms' is deprecated. Import from eg. 'langchain/llms/openai' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
whatsapp_bot  | ┌   Whatsapp ChatGPT & DALL-E 
.
.
app_bot  | 
whatsapp_bot  | Lembre-se de que a comunicação aberta e honesta é fundamental para resolver mal-entendidos e manter relacionamentos saudáveis.  | OpenAI request took 69159ms)
whatsapp_bot  | /app/node_modules/whatsapp-web.js/src/structures/Message.js:91
whatsapp_bot  |         this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
whatsapp_bot  |                                                                           ^
whatsapp_bot  | 
whatsapp_bot  | TypeError: data.id.id.substring is not a function
whatsapp_bot  |     at Message._patch (/app/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
whatsapp_bot  |     at new Message (/app/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
whatsapp_bot  |     at Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:699:16)
whatsapp_bot  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
whatsapp_bot  | 
whatsapp_bot  | Node.js v20.2.0

**Comment by emrekaramannnn** [comment]
I'm getting the same error. Help please!

**Comment by Hasbun** [comment]
Updating whatsapp-web.js solves the issue.

sudo npm update whatsapp-web.js

**Comment by helviodarochalima** [comment]
thank you very much
