### ISSUE TITLE
Why long prePrompts are not working?

### ISSUE THREAD

**Issue by Mr-Faisal-SGD** [askrella/whatsapp-chatgpt#240]
Can someone help me figure out that why long proprompts doesn't work and the default one works?

**Comment by helviodarochalima** [comment]
It takes me 5 minutes to receive a response on WhatsApp. I've noticed that the chat log shows a response from ChatGPT to the pre-prompt before the final response is sent to WhatsApp. Is there a parameter that can prevent receiving the response from the pre-prompt? Perhaps it would reduce the overall response time.

**Comment by navopw** [comment]
Token limit
