### ISSUE TITLE
Serp issue? "Importing from 'langchain/llms' is deprecated." How do we update this?

### ISSUE THREAD

**Issue by aodrasa** [askrella/whatsapp-chatgpt#241]
Unable to use the serp tool and am assuming it has to do with this depreciated langchain string, although please correct me if I'm wrong.

Which file needs to be updated to resolve this?
Cheers

**Comment by Farhan9599** [comment]
File Name: browser-agent.ts

"langchain/llms/openai"

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
