### ISSUE TITLE
Argo Tunnel error ||  https://speech-service.verlekar.com/ 

### ISSUE THREAD

**Issue by LVMuftu** [askrella/whatsapp-chatgpt#244]
![image](https://github.com/askrella/whatsapp-chatgpt/assets/89855552/9113128d-f37e-4741-b1f6-0d377722bb12)

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
