### ISSUE TITLE
I've been have running problem since yesterday

### ISSUE THREAD

**Issue by emrekaramannnn** [askrella/whatsapp-chatgpt#247]
`PS C:\Whatsapp> npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

file:///C:/Users/User/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:53395
        throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
              ^

Error: Parse failure: Octal literal in strict mode (3:13)
At file: C:/Whatsapp/node_modules/qrcode-terminal/lib/main.js
Contents of line 3:     black = "\033[40m  \033[0m",
    at ssrTransformScript (file:///C:/Users/User/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:53395:15)
    at ssrTransform (file:///C:/Users/User/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:53370:12)
    at Object.ssrTransform (file:///C:/Users/User/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:62770:20)
    at loadAndTransform (file:///C:/Users/User/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:41139:24)

Node.js v20.2.0
PS C:\Whatsapp>`

It worked until 2 days ago. but the "start" command now gives an error.

**Comment by JWPapi** [comment]
The issue is that the `qrcode-terminal` module hasn’t been updated since 2018 and no the vite linter complains. This is not in particular a problem of this repo, but it could still be improved. 

I’ve been changing in the `package.json` the line:

"qrcode-terminal": "^0.12.0",`
to 
"qrcode-terminal": "github:artradeapp/qrcode-terminal",`


as the second one is a fork that has changed the octal literals. Be aware that this is not an official node repo and has a security risk.

**Comment by emrekaramannnn** [comment]
> "qrcode-terminal": "github:artradeapp/qrcode-terminal",


**I made the change you said, but it still gives the error**



`PS C:\Whatsapp> npm start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

file:///C:/Users/ArtGraft/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:53395
        throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
              ^

Error: Parse failure: Octal literal in strict mode (3:13)
At file: C:/Whatsapp/node_modules/qrcode-terminal/lib/main.js
Contents of line 3:     black = "\033[40m  \033[0m",
    at ssrTransformScript (file:///C:/Users/ArtGraft/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:53395:15)
    at ssrTransform (file:///C:/Users/ArtGraft/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:53370:12)
    at Object.ssrTransform (file:///C:/Users/ArtGraft/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:62770:20)
    at loadAndTransform (file:///C:/Users/ArtGraft/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-c167897e.js:41139:24)

Node.js v20.2.0
PS C:\Whatsapp>`

**Comment by JWPapi** [comment]
did you run `npm install` after it?

**Comment by emrekaramannnn** [comment]
> did you run `npm install` after it?

yes.. I didn't have this error before, it worked until a few days ago.

**Comment by JWPapi** [comment]
maybe try this:

`npm install visionmedia/express`


For me the error was also there since yesterday or 2 days ago and this fixed it. I was also able to run it locally, but not on render.com as they are using vite

**Comment by emrekaramannnn** [comment]
PS C:\Whatsapp> npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\ArtGraft\User\Local\npm-cache\_logs\2023-06-01T09_45_59_191Z-debug-0.log

**Comment by emrekaramannnn** [comment]
> maybe try this:
> 
> `npm install visionmedia/express`
> 
> For me the error was also there since yesterday or 2 days ago and this fixed it. I was also able to run it locally, but not on render.com as they are using vite




PS C:\Whatsapp> npm install visionmedia/express
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\ArtGraft\AppData\Local\npm-cache\_logs\2023-06-01T09_48_18_851Z-debug-0.log

**Comment by JWPapi** [comment]
Ohh i pasted the wrong repo (fixed it now)

The right one would be 

`npm install artradeapp/qrcode-terminal`

but also this only works if you have git installed. If you don’t have you can try this:


npm install --save https://github.com/npm install artradeapp/qrcode-terminal

**Comment by emrekaramannnn** [comment]
> 

Where do I need to upload this?  https://github.com/artradeapp/qrcode-terminal

**Comment by emrekaramannnn** [comment]
> Ohh i pasted the wrong repo (fixed it now)
> 
> The right one would be
> 
> `npm install artradeapp/qrcode-terminal`
> 
> but also this only works if you have git installed. If you don’t have you can try this:
> 
> `npm install --save https://github.com/artradeapp/qrcode-terminal`




PS C:\> cd Whatsapp
PS C:\Whatsapp> npm install --save https://github.com/artradeapp/qrcode-terminal
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\User\AppData\Local\npm-cache\_logs\2023-06-01T10_03_42_576Z-debug-0.log
PS C:\Whatsapp> npm install https://github.com/artradeapp/qrcode-terminal
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\User\AppData\Local\npm-cache\_logs\2023-06-01T10_03_47_500Z-debug-0.log
PS C:\Whatsapp>

**Comment by emrekaramannnn** [comment]
@JWPapi Thank you for your help. But I still couldn't get it to work :)

**Comment by dluna1150** [comment]
I had the same problem, and I solved it. I asked gpt4 with the plugin browser and it fixed the problem in line 91 of a module.

**Comment by Dagolin** [comment]
This problem also affects docker when the new installation tries to use it, although in #254 it is indicated that it's possible to specify the version vite@0.31.1 to solve it, the image **image: ghcr.io/askrella/whatsapp-chatgpt:master** has been built in another version, also the node_modules.

**Comment by gilangryzqii** [comment]
> Ohh i pasted the wrong repo (fixed it now)
> 
> The right one would be
> 
> `npm install artradeapp/qrcode-terminal`
> 
> but also this only works if you have git installed. If you don’t have you can try this:
> 
> `npm install --save https://github.com/artradeapp/qrcode-terminal`

thanks it works!

**Comment by emrekaramannnn** [comment]
> Ohh i pasted the wrong repo (fixed it now)
> 
> The right one would be
> 
> `npm install artradeapp/qrcode-terminal`
> 
> but also this only works if you have git installed. If you don’t have you can try this:
> 
> `npm install --save https://github.com/artradeapp/qrcode-terminal`

https://github.com/askrella/whatsapp-chatgpt/issues/285

**Comment by emrekaramannnn** [comment]
> This problem also affects docker when the new installation tries to use it, although in #254 it is indicated that it's possible to specify the version vite@0.31.1 to solve it, the image **image: ghcr.io/askrella/whatsapp-chatgpt:master** has been built in another version, also the node_modules.

[This problem also affects docker when the new installation tries to use it, although in https://github.com/askrella/whatsapp-chatgpt/issues/254 it is indicated that it's possible to specify the version vite@0.31.1 to solve it, the image image: ghcr.io/askrella/whatsapp-chatgpt:master has been built in another version, also the node_modules.](https://github.com/askrella/whatsapp-chatgpt/issues/285)

**Comment by emrekaramannnn** [comment]
> This problem also affects docker when the new installation tries to use it, although in #254 it is indicated that it's possible to specify the version vite@0.31.1 to solve it, the image **image: ghcr.io/askrella/whatsapp-chatgpt:master** has been built in another version, also the node_modules.

https://github.com/askrella/whatsapp-chatgpt/issues/285

**Comment by NavinSiHive** [comment]
Whenever I am deleting message (for everyone), then this engine exits. Whereas, when I delete message (for me), then this engine does not exit, and continues to respond normal.

Can someone help to get rid of this issue ?

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
