### ISSUE TITLE
Compilation error with qrcode-terminal in Linux environment

### ISSUE THREAD

**Issue by ClaytonCassi** [askrella/whatsapp-chatgpt#251]
I am encountering a compilation error with the qrcode-terminal library when running in a Linux environment. This error appears to be related to an octal literal in strict mode.

Here are the details of the error message:

Jun  6 19:14:58 ip-x web: throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
Jun  6 19:14:58 ip-1x web: ^
Jun  6 19:14:58 ip-1x web: Error: Parse failure: Octal literal in strict mode (3:13)
Jun  6 19:14:58 ip-1x web: At file: /var/app/current/node_modules/qrcode-terminal/lib/main.js
Jun  6 19:14:58 ip-1x3 web: Contents of line 3:     black = "\033[40m  \033[0m",
Jun  6 19:14:58 ip-1xweb: at ssrTransformScript (file:///home/webapp/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53776:15)
Jun  6 19:14:58 ip-xweb: at ssrTransform (file:///home/webapp/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53751:12)
Jun  6 19:14:58 ip-1x web: at Object.ssrTransform (file:///home/webapp/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63307:20)
Jun  6 19:14:58 ip-1xweb: at loadAndTransform (file:///home/webapp/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53422:24)
Jun  6 19:14:58 ip-x web: Node.js v18.16.0
client_loop: send disconnect: Connection reset by peer

**Comment by elwizard33** [comment]
This issue seems duplicated, I posted a temporal workaround you can test here: https://github.com/askrella/whatsapp-chatgpt/issues/254#issuecomment-1585765922

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
