### ISSUE TITLE
Starting... is looping - No QR code displayed

### ISSUE THREAD

**Issue by drazy22** [askrella/whatsapp-chatgpt#253]
I installed from the beginning, and still looping on starting.
npm : v9.6.7
nodejs : v18.16.0
host : ubuntu server 20.04

I already npm the latest QR for whastapp

here is screenshot of my terminal:
https://cdn.discordapp.com/attachments/1076823706355105833/1116303042858459186/Capture_decran_2023-06-08_a_15.15.27.png

Do you have any idea how to fix it?

**Comment by elwizard33** [comment]
Have you been able to scan the code once? This happened to me but I was able to authenticate once, then if I want to make it work again I have to kill the terminal and start a new one and it works, but I'm doing some debugging to see why this happens

**Comment by tilman42** [comment]
This might be a stupid question but what exactly do you mean by "killing" the terminal? An how would I do that? Having the same issue mentioned above.

**Comment by apfordz** [comment]
I am having the same issue but found a work around fix. 

1. Exit terminal
2. Navigate to Linked Devices on your mobile WA
3. Log out from the linked device that is this service (usually chrome) 
4 Re-start terminal and npm start run
5. Re-authenticate by scanning QR code

This seems to stop the starting loop but is a little annoying for every re-start. 

Hope it helps someone.

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
