### ISSUE TITLE
SerpAPI API key not set.

### ISSUE THREAD

**Issue by Farhan9599** [askrella/whatsapp-chatgpt#259]
I have added the SerpAPI Key into the .env file but the same error continues.

**Comment by Pompeii1631** [comment]
I have the same issue.

**Comment by gmarkone** [comment]
Me too, did anyone solve it so far?

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!

**Comment by DhaiDev** [comment]
I remove .env-example and add new .env and copy all from .env-example to .env
