### ISSUE TITLE
Available as a Docker Image?

### ISSUE THREAD

**Issue by henkisdabro** [askrella/whatsapp-chatgpt#27]
It would be amazing if there were a Docker image and docker-compose file available for easy set for us less tech savvy!

**Comment by miikkuu** [comment]
@navopw  Would like to work on this.

**Comment by navopw** [comment]
@miikkuu Feel free to create a PR for this.

Maybe I will also do a Dockerfile :)

**Comment by RG7279805** [comment]
@navopw i have made the changes which were asked and created a PR too 
mind checking it out
