### ISSUE TITLE
parse failure there is some compatibility issue of QRcode terminal package with Vite

### ISSUE THREAD

**Issue by RKP64** [askrella/whatsapp-chatgpt#272]
![Screenshot (28)](https://github.com/askrella/whatsapp-chatgpt/assets/121541878/277d68ed-d8ba-4f6f-a88c-0e2a31eb38da)

**Comment by kingofkillers91** [comment]
Having the same issue. Did you figure this out?

**Comment by thenetguy** [comment]
Having the same issue. Did you figure this out?

**Comment by thenetguy** [comment]
found the fix in another thread , change the docker file to specify the vite-node version . npm install vite-node@0.31.1

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
