### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by AlexandriaPedro** [askrella/whatsapp-chatgpt#278]
I dowload everything and followed the steps, but every time I send a message to myself I get this answer: "Request failed with status code 429". 

I can use !gpt, !dalle2 and don't change anything.
I already use another OpenAI account but nothing worked.

Can someone help me on this? I need to dowload another thing that is not explicit in the doc?

Btw, my last hope is to find some intructions here.

**Comment by kingofkillers91** [comment]
Did you figure this out?

**Comment by adamshand** [comment]
I've been using the bot for a few months and just started getting the error today.  Not sure what's changed yet, trying to figure it out.

**Comment by adamshand** [comment]
This is an error from OpenAI, check your billing status.  I'd hit my hard quota and needed to increase it.

**Comment by NavinSiHive** [comment]
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
