### ISSUE TITLE
stuck in login

### ISSUE THREAD

**Issue by maycon600** [askrella/whatsapp-chatgpt#289]
yesterday I was using it normally, but today it doesn't connect anymore, it reads the qrcode but it keeps logging in infinitely, I tried to copy the repository again several times, I tested it on 5 cell phones, I also tried to start it on 3 computers and the same thing every time.

**Comment by maycon600** [comment]
I managed to fix it, apparently whatsapp-web.js broke, so to solve it is simple, open packet.json and add the following line: "whatsapp-web.js": "https://github.com/Julzk/whatsapp- web.js/tarball/jkr_hotfix_7"
then run npm install
![WhatsApp Image 2023-08-23 at 10 43 51 AM](https://github.com/askrella/whatsapp-chatgpt/assets/73262700/4cf85ff5-f713-4a5c-b286-246739f98eb8)

**Comment by PGRjoystick** [comment]
i've applied the hotfix, but the openai api response is 429 or too many request. i do have any remaning balance left in my keys. do you have any of these issues since you applied the hotfix ?

> I managed to fix it, apparently whatsapp-web.js broke, so to solve it is simple, open packet.json and add the following line: "whatsapp-web.js": "https://github.com/Julzk/whatsapp- web.js/tarball/jkr_hotfix_7" then run npm install ![WhatsApp Image 2023-08-23 at 10 43 51 AM](https://user-images.githubusercontent.com/73262700/262706737-4cf85ff5-f713-4a5c-b286-246739f98eb8.jpeg)

**Comment by felixlu07** [comment]
That helped !!! THANKS! @maycon600

**Comment by sk77github** [comment]
so nice ,think you @maycon600  that work for me.

by the way, how did you find this can be work?

 i mean i try the difference phone ,difference server like you, and nothing. i am also reading the source code ,just find that do not receive event from whatsapp ,but do not know what can be do.  so , i find issues and come here.

**Comment by jerryrat** [comment]
logging working but answer not

**Comment by jerryrat** [comment]
npm i whatsapp-web.js@1.22.2-alpha.0

**Comment by envieme** [comment]
Had the same problem, tried your fix. Now the "logging in..." message is gone. But... Keeps saying "Waiting for QR code to be scanned" even after scanning and whatsapp mobile saying linked to the server headless browser.

> I managed to fix it, apparently whatsapp-web.js broke, so to solve it is simple, open packet.json and add the following line: "whatsapp-web.js": "https://github.com/Julzk/whatsapp- web.js/tarball/jkr_hotfix_7" then run npm install ![WhatsApp Image 2023-08-23 at 10 43 51 AM](https://user-images.githubusercontent.com/73262700/262706737-4cf85ff5-f713-4a5c-b286-246739f98eb8.jpeg)

**Comment by maycon600** [comment]
> so nice ,think you @maycon600 that work for me.
> 
> by the way, how did you find this can be work?
> 
> i mean i try the difference phone ,difference server like you, and nothing. i am also reading the source code ,just find that do not receive event from whatsapp ,but do not know what can be do. so , i find issues and come here.

I looked for other similar programs and one of them had the solution

**Comment by RadientBrain** [comment]
yes this works:- `"whatsapp-web.js": "github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_7"`

along with `npm install vite-node@0.31.1`

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
