### ISSUE TITLE
My whatsapp app can not recognise the QR code

### ISSUE THREAD

**Issue by BYChern** [askrella/whatsapp-chatgpt#292]
I am working on windows and everything works just fine but the QR code generated to login  can't be recognised by my phone
and it looks like this 
![image](https://github.com/askrella/whatsapp-chatgpt/assets/119783767/153c868a-efc9-4eb1-a596-de7974e55bf5)

**Comment by thenetguy** [comment]
open another terminal window and run `docker logs container_name` it will give a much cleaner QR code

**Comment by BYChern** [comment]
I am not running it with docker, is there any another solutions?

**Comment by navopw** [comment]
Try a different terminal, for example git-bash on windows.

https://gitforwindows.org/
