### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')

### ISSUE THREAD

**Issue by NavinSiHive** [askrella/whatsapp-chatgpt#298]
Whenever I am deleting message (for everyone), then this engine exits. Whereas, when I delete message (for me), then this engine does not exit, and continues to respond normal.

Can someone help to get rid of this issue ?

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
