### ISSUE TITLE
add a pipeline and some unit tests ? 

### ISSUE THREAD

**Issue by wassef911** [askrella/whatsapp-chatgpt#34]
any suggestions on what to use? Mocha? Tape?

**Comment by navopw** [comment]
Mocha would be great :)

**Comment by jwalahe** [comment]
+1

Are you aiming for 80% global coverage? @navopw @wassef911

**Comment by navopw** [comment]
Would be nice but this project is currently in rapid development phase.

Will start with the tests in a few days :D

**Comment by navopw** [comment]
There already was a PR for tests but I had to decline because the methods changed.

https://github.com/askrella/whatsapp-chatgpt/pull/49

Will merge this sooner or later tho.

**Comment by jwalahe** [comment]
Makes sense!

**Comment by wassef911** [comment]
understood
