### ISSUE TITLE
Chatgpt non showing up among my others chats.

### ISSUE THREAD

**Issue by kingofkillers91** [askrella/whatsapp-chatgpt#35]
Hi there,
it seems that what i have done so far is working because i get the message " [Whatsapp ChatGpt] Client is Ready! " and all the texts that i receive are being written in my terminal and the bot is replying on my behalf but the actual chat is not showing up, so i can't ask question. What is it that i could've done wrong? Also, i do i stop my bot to answer when the whatsapp session is active? (for now i just interrupted the session. Let me know. 
Thank you

**Comment by navopw** [comment]
It is not showing up as separate chat.

People can message you with e.g. "!gpt How are you today" and the bot will answer in behalf of you
