### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by fachrulabizar** [askrella/whatsapp-chatgpt#352]
I followed the install here but when npm run start then scan barcode an error appears

https://askrella.github.io/whatsapp-chatgpt/#/pages/installation

![Screenshot 2024-08-01 193921](https://github.com/user-attachments/assets/098b8b7f-47c4-49c7-bd33-609c6c1ee471)

**Comment by MikelCalvo** [comment]
Hi, I have just merged a PR updating the whatsapp-web.js library into the latest version, If you can, please pull the latest changes and try again, thanks!

**Comment by fachrulabizar** [comment]
okay that worked, thanks
