### ISSUE TITLE
Is there a way to send yourself questions (not just receive)?

### ISSUE THREAD

**Issue by henkisdabro** [askrella/whatsapp-chatgpt#40]
I would like a way to interact with the bot for myself, not just set this up for _other people_ to use, how is that done, do we need to setup whatsapp for another phone number? Or is there a way to set up whatsapp for business to make that work?

**Comment by Zain-ul-din** [comment]
@henkisdabro  ok I'll do this for you

**Comment by navopw** [comment]
I merge add it today. 👍

**Comment by navopw** [comment]
Now you can also message yourself.

Please note that if PREFIX_ENABLED is false only GPT will answer. Not DALL-E.

**Comment by Zain-ul-din** [comment]
@navopw that's good
