### ISSUE TITLE
le navigateur s'ouvre puis se referme 

### ISSUE THREAD

**Issue by xxxkulo** [askrella/whatsapp-chatgpt#5]
Bonjour,

J'ai suivi toutes les étapes sur Mac OS. Le programme fonctionne bien, mais la fenêtre du navigateur s'ouvre, puis se ferme directement. Le terminal me montre ceci :
ChatGPTError : Jeton de session ChatGPT non valide
Code d'état : 401

**Comment by navopw** [comment]
401 means your credentials are wrong. Check your email and password in the .env file like instructed in the README.md.

**Comment by KurtFerr** [comment]
Thanks!
