### ISSUE TITLE
Providing Custom Context

### ISSUE THREAD

**Issue by Zain-ul-din** [askrella/whatsapp-chatgpt#50]
It would be nice if we let users add their own `context`.

## Example
```typescript
const custom_context = `
 Context:
 RandomsTS is a free and open-source framework for building restful APIS 
 using typescript and class-based object-oriented programming.
 Key Features: file-base routing, Hot-reloading, Type safety, Intuitive APIs.
 
 NOTE! Only answer from the given context
 question: 
 <add user_message here>
`

const canUseCustomContext = messageStr.includes("RandomsTS");
if (canUseCustomContext) 
{
  // add custom_context before user message
  await handleMessageGPT(message, custom_context+prompt)
}

```

## Results

```bash
 message:- what is RandomsTS
 
 reply:- RandomsTS is a free and open-source framework for building restful APIS 
 using typescript and class-based object-oriented programming.
```

**Comment by Zain-ul-din** [comment]
@navopw do you have any APIS design for this?

**Comment by navopw** [comment]
We can add a `PRE_PROMPT` to environment variables which is sent to GPT on initialization of a conversation.

Did I understand this issue correct?

**Comment by Zain-ul-din** [comment]
@navopw that's correct but, how to decide when to use custom_context?

**Comment by navopw** [comment]
We can name the env variable `CUSTOM_CONTEXT`.

If the environment variable is set, **always** use custom context.

This is nice for creating actual chat bots that understand custom problems/solutions.

**Comment by Zain-ul-din** [comment]
what if we add this statement before the message?

```
use this context only if the question provided below seems to be from the context.
```

**Comment by Zain-ul-din** [comment]
Assign it to me and also merge my previous PR.
