### ISSUE TITLE
loading Spinner while loading chat

### ISSUE THREAD

**Issue by Zain-ul-din** [askrella/whatsapp-chatgpt#59]
## Problem

When the user scans `QR` after this what's the app takes some time to load the chat. 

## Solution

It would be nice to add a `loading spinner` while the chat is being loaded for a better experience.

## Example

```typescript
client.on('loading_screen', (percent, message) => {
        // show spinner here
});
```

**Comment by navopw** [comment]
It only takes like 5 seconds, I think spinner is unnecessary 😢

**Comment by Zain-ul-din** [comment]
This is for those who use the 3G connection.

**Comment by navopw** [comment]
Okay fine :D

**Comment by marcomafessolli** [comment]
I can take this one!

**Comment by Zain-ul-din** [comment]
ok
