### ISSUE TITLE
Automatically deciding what model to use

### ISSUE THREAD

**Issue by piercegov** [askrella/whatsapp-chatgpt#67]
Currently, if you don't provide a prefix, the assistant will only use GPT. However, it is possible to analyze the user's request and decide which model to use.

Alternatively, maybe even sending a (hidden) request to GPT and letting it decide if it should handle the request or if DALLE should could be a viable solution. Obviously, (regardless of approach) this could be a relatively large feature, especially if you would want to increase the accuracy of these 'guesses' by providing additional context to whatever model/regex/whatever such as previous messages.

This would make the assistant feel more complete as you can have a more natural 'conversation' with it.

Sorry if this is a duplicate suggestion, I could not find one similar to this.

**Comment by navopw** [comment]
Great idea!

It would add a little bit too much complexity for this project right now.
We would have to test the accuracy and so much more.

Maybe in future or when actual ChatGPT API releases :)

I will keep this in mind!

**Comment by RG7279805** [comment]
There is one more problem i could think for a single request you have call the API twice
