### ISSUE TITLE
I would like to propose `dalle-config` instead of `config`,  we may have the same for gpt or others ai assistants.

### ISSUE THREAD

**Issue by manishaarya9899359346** [askrella/whatsapp-chatgpt#75]
I would like to propose `dalle-config` instead of `config`,  we may have the same for gpt or others ai assistants.

_Originally posted by @andrewssobral in https://github.com/askrella/whatsapp-chatgpt/issues/62#issuecomment-1436026319_

**Comment by navopw** [comment]
Yes but we can have a parameter like `!config <gpt/dalle> <property> <value>`

So !config is fine (or !aiconfig)
