### ISSUE TITLE
Voice message transcription feature

### ISSUE THREAD

**Issue by navopw** [askrella/whatsapp-chatgpt#78]
Already working on feature/whisper branch.

![image](https://user-images.githubusercontent.com/6507938/220114828-791da661-452f-4b0e-8a5c-06baa035547d.png)

- We need some documentation in docs/whisper.md on how to install whisper.
    - Windows, Linux, Mac
- Needs better code structure, i just drafted it
- Needs more testing

**Comment by andrewssobral** [comment]
@navopw This would be really cool!

**Comment by navopw** [comment]
Released it, have fun.

Create issues on errors.
