### ISSUE TITLE
Exceeded Current Quota

### ISSUE THREAD

**Issue by Sam-Varghese** [askrella/whatsapp-chatgpt#81]
I started the project locally, and successfully got it set up. But when I try to use gpt, here's what I get

![image](https://user-images.githubusercontent.com/79152648/220172288-e5ede84e-bd68-4793-91c6-224f4254d91a.png)

I don't even use ChatGPT so often that it should show me the error *Exceeded Current Quota*.

Kindly help me out

Regards
Sam Varghese

**Comment by navopw** [comment]
You have to setup a payment method here:

https://platform.openai.com/account/billing/overview

You have no funds in your OpenAI account.
