### ISSUE TITLE
Dalle not showing pics

### ISSUE THREAD

**Issue by kingofkillers91** [askrella/whatsapp-chatgpt#82]
Hi there, 
the !dalle command works because it answers to me but the pics i try to generate don't show up. Just a description of the actual photo i requested comes out. What could be wrong?
![WhatsApp Image 2023-02-20 at 10 54 07 PM](https://user-images.githubusercontent.com/48602339/220204295-5a3a134d-97b2-4c7a-8b34-274f3874b150.jpeg)

**Comment by navopw** [comment]
You have PREFIX_ENABLED=false in your .env file.

Thats why the bot accepts your messages as GPT prompts and the commands '!gpt' and '!dalle' dont work.

Enable the prefixes by setzing it to true.

Then use !gpt and !dalle commands 😃

**Comment by kingofkillers91** [comment]
it's enabled, this is what i wrote on my .env ---> PREFIX_ENABLED=True

**Comment by kingofkillers91** [comment]
it is, i wrote like this: PREFIX_ENABLED=true

**Comment by navopw** [comment]
Okay, let me double check this.

**Comment by kingofkillers91** [comment]
I can send more screenshots  if you need

**Comment by connorv001** [comment]
> I can send more screenshots if you need

What happens if you run !dalle ? Can you send some logs?

**Comment by kingofkillers91** [comment]
when i run the !dalle command is not detected from the bot unlike !gpt that works just fine. 

Whatsapp ChatGPT] Client is ready!
[Whatsapp ChatGPT] Received prompt from 393275312509@c.us: chi è ronaldo
[Whatsapp ChatGPT] Answer to 393275312509@c.us: Ronaldo è un famoso calciatore professionista brasiliano che gioca attualmente per la Juventus. Ha vinto più di 20 trofei di club, tra cui 5 campionati italiani, 4 Coppe Italia, 4 Supercoppe italiane e 1 Champions League. Inoltre, è stato premiato come miglior calciatore del mondo per ben 5 volte.                                                                                                                              
[Whatsapp ChatGPT] ChatGPT took 9266ms
[Whatsapp ChatGPT] Received prompt from 393275312509@c.us: 2 times 2
[Whatsapp ChatGPT] Answer to 393275312509@c.us: 2 volte 2 è uguale a 4.
[Whatsapp ChatGPT] ChatGPT took 1662ms

![WhatsApp Image 2023-02-21 at 6 52 33 PM](https://user-images.githubusercontent.com/48602339/220422787-cd90ba39-3d9d-48d6-a7aa-e9bfb1ca5815.jpeg)

**Comment by navopw** [comment]
Should be fixed now!

Please try again with latest master branch.

PREFIX_ENABLED was a little bit broken, I think.

**Comment by navopw** [comment]
Also join our Discord if you want to get better and quicker support from the community :)

https://discord.gg/9VJaRXKwd3

**Comment by navopw** [comment]
This kind of behaviour with !dalle is still a little bit weird, hm...

**Comment by kingofkillers91** [comment]
Working now!! Thanks
