### ISSUE TITLE
A way to store the session or login details.

### ISSUE THREAD

**Issue by Cosm1cBug** [askrella/whatsapp-chatgpt#83]
When we turn off the program or it got interrupted by any other means, we have to scan the code again, instead if it saves the login details in a file, it will be good.

**Comment by byt3magic** [comment]
I'll take a look and maybe add this feature. My branch is byt3magic, and I also have a [fork here](https://github.com/byt3magic/whatsapp-chatgpt).

**Comment by navopw** [comment]
Will merge it right now.
