### ISSUE TITLE
WhatsApp could block users?

### ISSUE THREAD

**Issue by byt3magic** [askrella/whatsapp-chatgpt#85]
This repository uses [pedroslopez/whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) repository.

README of whatsapp-web.js: 
```
It uses Puppeteer to run a real instance of Whatsapp Web to avoid getting blocked.

NOTE: I can't guarantee you will not be blocked by using this method, although it has worked for me. WhatsApp does not allow bots or unofficial clients on their platform, so this shouldn't be considered totally safe.
```

You should mention that users can get blocked for using askrella/whatsapp-chatgpt.

**Comment by navopw** [comment]
Added it to README. Thanks!

**Comment by Re1da** [comment]
> This repository uses [pedroslopez/whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) repository.
> 
> README of whatsapp-web.js:
> 
> ```
> It uses Puppeteer to run a real instance of Whatsapp Web to avoid getting blocked.
> 
> NOTE: I can't guarantee you will not be blocked by using this method, although it has worked for me. WhatsApp does not allow bots or unofficial clients on their platform, so this shouldn't be considered totally safe.
> ```
> 
> You should mention that users can get blocked for using askrella/whatsapp-chatgpt.
