### ISSUE TITLE
Add option to choose who the bot should answer

### ISSUE THREAD

**Issue by navopw** [askrella/whatsapp-chatgpt#99]
Environment variable:
```
ANSWER_MODE=
```

Options:
- yourself = Only yourself
- chats = Yourself and Chats
- groups = Yourself, Chats and Groups

**Comment by marcomafessolli** [comment]
I can take this one @navopw

**Comment by laukik-target** [comment]
Thanks @navopw  , I think that's what we want

**Comment by badermq76** [comment]
How about adding a whitelist of numbers to choose who the bot should answer under the chat?

**Comment by Seitk** [comment]
https://github.com/askrella/whatsapp-chatgpt/pull/144
